package net.std.clabe.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2018-10-18T17:08:15.810-06:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://generaClabe.spei.ws.izel.net/", name = "GeneraClabeIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GeneraClabeIfz {

    @WebResult(name = "GeneraClabeResponse", targetNamespace = "http://generaClabe.spei.ws.izel.net/", partName = "parameters")
    @WebMethod
    public GeneraClabeResponse procesar(
        @WebParam(partName = "parameters", name = "GeneraClabeRequest", targetNamespace = "http://generaClabe.spei.ws.izel.net/")
        GeneraClabeRequest parameters
    );
}
