spring.application.name=ms-asp-digitalizacion-bloqueo-cuenta

server.servlet.context-path=/api
server.port=8087
spring.datasource.url= ${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# =========================
# SECURITY CONFIG
# =========================
auth.user: ${AUTH_USER}
auth.password: ${AUTH_PASSWORD}

jwt.secret: ${JWT_SECRET}
jwt.expiration: 3600000

# =========================
# EIYU CONFIG
# =========================
eiyu.jwt.secret=${EIYU_JWT_SECRET_KEY}
eiyu.jwt.issuer=${EIYU_JWT_ISSUER}
eiyu.jwt.audience=${EIYU_JWT_AUDIENCE}

eiyu.url.activa.cuenta=${EIYU_URL_ACTIVA_CUENTA}
