server.port:8080
spring.datasource.url=jdbc:postgresql://35.222.203.75:5432/admdocumentoupload-db
spring.datasource.username=admdocument-db
spring.datasource.password=4dmd0cum3nt-db
spring.cloud.config.enabled=false
archivo.pathGuardado = /tmp/ 
archivo.bucketName=nombre del bucktet
