#///////////////////////////////USUARIO PROCESOS CERO
USUARIO_DEP_TRANSFERENCIA_AHORRO=4160
#///////////////////////////////SUCURSAL VIRTUAL PARA CUENTAS SIMPLIFICADA
SUCURSAL_VIRTUAL_CODI=500
#///////////////////////////////BANCO DE DEPOSITO DE AHORRO
BANCO_DEP_TRANSFERENCIA_AHORRO=0
BANCO_DISP_TRANSFERENCIA_AHORRO=0
#///////////////////////////////CAJA DEPOSITO DE AHORRO
CAJA_DEP_TRANSFERENCIA_AHORRO=1
#///////////////////////////////FORMA DE PAGO DE DEPOSITO DE AHORRO
FORMA_APGO_DEP_TRANSFERENCIA_AHO=4
FORMA_APGO_DISP_TRANSFERENCIA_AHO=4
#///////////////////////////////MOVIMIENTO DEPOSITO TRANSFERENCIA
MOVIMIENTO_DEP_TRANSFERENCIA_AHORRO=17
MOVIMIENTO_DISP_TRANSFERENCIA_AHORRO=16
MOVIMIENTO_DISP_TRANSFERENCIA_SPEI=34
VAL_OCR_INE=104
#///////////////////////////////DATOS PERFIL TRANSACCIONAL
ACTIVIDAD_ID=500
GIRO_ID=4404
CVE_DESTINO=173
OCUPACION_ID=273																																		11
#///////////////////////////////DATOS PARA NOTIFICACION POR CORREO A CALL CENTER
REMITENTE_EMAIL_CALLCENTER=procesos@aspintegraopciones.com
DESTINATARIO_EMAIL_CALLCENTER=call_center@aspintegraopciones.com
ASUNTO_EMAIL_CALLCENTER=Nueva apertura de cuenta
PRODUCTO_CUENTA_FACIL=Cuenta Facil
ID_PRODUCTO_CUENTA_FACIL=6
TRX_VERIFICA_DATOS_CUENTA_FACIL=608
USR_SERV_AUT=ASP
PSW_SERV_AUT=a5p2017$
ID_EMPRESA=1
USR_CLAVE=ASISTEMAS
ID_USR=9
ID_SUCURSAL=500
IP_HOST=0.0.0.0
ID_CANAL=1
CAMBIO_TEL_CODI_CLV=CTC
CAMBIO_COL_ID_CLV=CCI
CAMBIO_CORREO_CLV=CCC
CAMBIO_DOMICILIO_CLV=CDC