# Conexion cero
spring.cero.jdbc-url=jdbc:postgresql://pg-cero.integraopciones.mx:5432/cero?ApplicationName=CeroAhorroWS
spring.cero.username=apps
spring.cero.password=apps
spring.cero.driver-class-name=org.postgresql.Driver

spring.cero.pooling.pool-name=CeroPoolHCP
spring.cero.pooling.maximum-pool-size=2
spring.cero.pooling.minimumIdle=1
spring.cero.pooling.idleTimeout=100000
spring.cero.pooling.max-lifetime=600000
spring.cero.pooling.connection-timeout=300000

# Conexion izelSTI

spring.izelsti.jdbc-url=jdbc:postgresql://pg-izelSTI.integraopciones.mx:5432/izelSTI?ApplicationName=CeroAhorroWS
spring.izelsti.username=apps
spring.izelsti.password=apps
spring.izelsti.driver-class-name=org.postgresql.Driver

spring.izelsti.pooling.pool-name=IzelSTIPoolHCP
spring.izelsti.pooling.maximum-pool-size=2
spring.izelsti.pooling.minimumIdle=1
spring.izelsti.pooling.idleTimeout=100000
spring.izelsti.pooling.max-lifetime=600000
spring.izelsti.pooling.connection-timeout=300000

# Conexion procrea

spring.procrea.jdbc-url: jdbc:postgresql://pg-procrea.integraopciones.mx:5432/procrea?ApplicationName=CeroAhorroWS
spring.procrea.username: apps
spring.procrea.password: apps
spring.procrea.driver-class-name: org.postgresql.Driver

spring.procrea.pooling.pool-name: ProcreaPoolHCP
spring.procrea.pooling.maximum-pool-size: 2
spring.procrea.pooling.minimumIdle: 1
spring.procrea.pooling.idleTimeout: 100000
spring.procrea.pooling.max-lifetime: 600000
spring.procrea.pooling.connection-timeout: 30000

#constantes para los servicios de seguridad de cero
cero.estatus.activo=ALTA
cero.estatus.baja=BAJA