WS_LOGIN = http://172.148.49.3:8080/WS2FA/WS2FA?wsdl
GESTION_ASESOR_WS=http\://192.168.0.133\:8080/GestionAsesorWS/rest
WS_CON_CAT=http\://192.168.0.133\:8080/JuiciosWS/rest/consultarDatosCatalogo
WS_ACT_CAT=http\://192.168.0.133\:8080/JuiciosWS/rest/actualizaDatoCatalogo
WS_INS_CAT=http\://192.168.0.133\:8080/JuiciosWS/rest/insertaDatoCatalogo
WS_ELI_CAT=http\://192.168.0.133\:8080/JuiciosWS/rest/eliminaDatoCatalogo
WS_GEST=http\://192.168.0.133\:8080/JuiciosWS/rest/consultarGestores
WS_CON_JUI =http\://192.168.0.133\:8080/JuiciosWS/rest/consultarJuicios
WS_REG_JUI=http\://192.168.0.133\:8080/JuiciosWS/rest/registrarJuicio
WS_MOD_JUI=http\://192.168.0.133\:8080/JuiciosWS/rest/modificarJuicio
WS_CON_EMPSUC=http\://192.168.0.133\:8080/JuiciosWS/rest/consultarCatalogos
WS_CON_CON=http://192.168.0.133:8080/JuiciosWS/rest/consultarContrato
WS_CON_DEM=http://192.168.0.133:8080/JuiciosWS/rest/consultarDemandados
WS_ELI_DEM=http://192.168.0.133:8080/JuiciosWS/rest/eliminarDemandado
WS_CON_AVA=http://192.168.0.133:8080/JuiciosWS/rest/consultarAvances
WS_LIB_AVA=http://192.168.0.133:8080/JuiciosWS/rest/liberarAvance
WS_REG_AVA=http://192.168.0.133:8080/JuiciosWS/rest/registrarAvance
WS_ACT_AVA=http://192.168.0.133:8080/JuiciosWS/rest/modificarAvance
WS_REG_DOC=http://192.168.0.133:8080/JuiciosWS/rest/registrarDoctos
WS_CON_DOC=http://192.168.0.133:8080/JuiciosWS/rest/consultarDoctos
WS_ACT_DOC=http://192.168.0.133:8080/JuiciosWS/rest/modificarDocto
WS_REG_COM=http://192.168.0.133:8080/JuiciosWS/rest/registrarComentario
WS_CON_COM=http://192.168.0.133:8080/JuiciosWS/rest/consultarComentarios
WS_ADMIN_SEG = http://172.148.49.3:8080/AdminSegWS/rest
WS_NUCLE_CEN = http://172.148.49.3:8080/NucleoCentralWS/rest
WS_NUCLEO_CENTRAL = http://172.148.49.3:8080/NucleoCentralWS/rest
AUTORIZACION_WS = http://sr-modulo-autorizaciones.integraopciones.mx:8080/MonAutorizacionesWS/rest
CONSULTA_SALDO_CUENTA= http://sr-ahorrows.integraopciones.mx:8081/AhorroSwitchCeroWS/rest/consultaSaldo
CONSULTA_TARJETAS_DOCK = http://172.17.7.100:8080/admin-plasticos-services/consultarEstatusTarjetas
BLOQUEA_TARJETA_DOCK = http://172.17.7.100:8080/admin-plasticos-services/bloquear-tarjeta
DESBLOQUEA_TARJETA_DOCK = http://172.17.7.100:8080/admin-plasticos-services/desbloquear-tarjeta
CAMBIO_CONTRASENA_LDAP = http://172.17.7.183:8080/AdminSegWS/rest/ldap/modifica/
APLICATIVO_ID=1
LDAP_URL = ldap://172.148.49.3:10389
LDAP_DN = uid=USER,ou=users,ou=system,dc=aspdesarrollo,dc=com
LDAP_ADMIN = admin
LDAP_PWD = admin123
CANAL_ID = 1
CANAL_SUC_ID = 2
CANAL_COM_ID = 3
SERVICIO_TOKEN = 0
BYPASS = 1
ALTA = 1
TIME_SESSION = 20

#OPERACIONES
TRX_NUEVOCANAL = 1
TRX_MODIFICACANAL = 2
TRX_BAJACANAL = 3
TRX_CONSULTACANAL = 4
TRX_NUEVOGRUPO = 5
TRX_MODIFICAGRUPO = 6
TRX_BAJAGRUPO = 7
TRX_CONSULTAGRUPO = 8
TRX_NUEVOHORARIO = 9
TRX_MODIFICAHORARIO = 10
TRX_BAJAHORARIO = 11
TRX_CONSULTAHORARIO = 12
TRX_NUEVOMENSAJE = 13
TRX_MODIFICAMENSAJE = 14
TRX_BAJAMENSAJE = 15
TRX_CONSULTAMENSAJE = 16
TRX_NUEVOPERFIL = 17
TRX_MODIFICAPERFIL = 18
TRX_BAJAPERFIL = 19
TRX_CONSULTAPERFIL = 20
TRX_NUEVOTIPOMENSAJE = 21
TRX_MODIFICATIPOMENSAJE = 22
TRX_BAJATIPOMENSAJE = 23
TRX_CONSULTATIPOMENSAJE = 24
TRX_NUEVATRANSACCION = 25
TRX_MODIFICATRANSACCION = 26
TRX_BAJATRANSACCION = 27
TRX_CONSULTATRANSACCION = 28
TRX_NUEVOUSRTERM = 29
TRX_MODIFICAUSRTERM = 30
TRX_BAJAUSRTERM = 31
TRX_CONSULTAUSRTERM = 32
TRX_NUEVOGRUPOPUESTO = 33
TRX_MODIFICAGRUPOPUESTO = 34
TRX_BAJAGRUPOPUESTO = 35
TRX_CONSULTAGRUPOPUESTO = 36
TRX_NUEVOMATRIZSEG = 37
TRX_MODIFICAMATRIZSEG = 38
TRX_BAJAMATRIZSEG = 39
TRX_CONSULTAMATRIZSEG = 40
TRX_CARGAMATRIZSEG = 41
TRX_ASIGNARPERFILES = 42
TRX_ASIGNARTRXS = 43
TRX_AUDITORIA = 44
TRX_LOGIN = 45
TRX_LOGOUT = 46
TRX_NUEVOPERFILPUESTO = 47
TRX_MODIFICAPERFILPUESTO = 48
TRX_BAJAPERFILPUESTO = 49
TRX_CONSULTAPERFILPUESTO = 50

TRX_NUEVOALERTA = 51
TRX_MODIFICAALERTA = 52
TRX_BAJAALERTA = 53
TRX_CONSULTAALERTA = 54
TRX_NUEVOAREA = 55
TRX_MODIFICAAREA = 56
TRX_BAJAAREA = 57
TRX_CONSULTAAREA = 58
TRX_NUEVOBANCO = 59
TRX_MODIFICABANCO = 60
TRX_BAJABANCO = 61
TRX_CONSULTABANCO = 62
TRX_NUEVOCALENDARIO = 63
TRX_MODIFICACALENDARIO = 64
TRX_BAJACALENDARIO = 65
TRX_CONSULTACALENDARIO = 66
TRX_NUEVOCANALNUCLEO = 67
TRX_MODIFICACANALNUCLEO = 68
TRX_BAJACANALNUCLEO = 69
TRX_CONSULTACANALNUCLEO = 70
TRX_NUEVOCARGO = 71
TRX_MODIFICACARGO = 72
TRX_BAJACARGO = 73
TRX_CONSULTACARGO = 74
TRX_NUEVOCIUDAD = 75
TRX_MODIFICACIUDAD = 76
TRX_BAJACIUDAD = 77
TRX_CONSULTACIUDAD = 78
TRX_NUEVOCOLONIA = 79
TRX_MODIFICACOLONIA = 80
TRX_BAJACOLONIA = 81
TRX_CONSULTACOLONIA = 82
TRX_NUEVOCOMISIONISTA = 83
TRX_MODIFICACOMISIONISTA = 84
TRX_BAJACOMISIONISTA = 85
TRX_CONSULTACOMISIONISTA = 86
TRX_NUEVOCOMOSEENTERO = 87
TRX_MODIFICACOMOSEENTERO = 88
TRX_BAJACOMOSEENTERO = 89
TRX_CONSULTACOMOSEENTERO = 90
TRX_NUEVOCOMPANIATEL = 91
TRX_MODIFICACOMPANIATEL = 92
TRX_BAJACOMPANIATEL = 93
TRX_CONSULTACOMPANIATEL = 94
TRX_NUEVOCUENTASBAN = 95
TRX_MODIFICACUENTASBAN = 96
TRX_BAJACUENTASBAN = 97
TRX_CONSULTACUENTASBAN = 98
TRX_NUEVOEMPLEADO = 99
TRX_MODIFICAEMPLEADO = 100
TRX_BAJAEMPLEADO = 101
TRX_CONSULTAEMPLEADO = 102
TRX_NUEVOEMPRESA = 103
TRX_MODIFICAEMPRESA = 104
TRX_BAJAEMPRESA = 105
TRX_CONSULTAEMPRESA = 106
TRX_NUEVOEQUIPO = 107
TRX_MODIFICAEQUIPO = 108
TRX_BAJAEQUIPO = 109
TRX_CONSULTAEQUIPO = 110
TRX_NUEVOESTADOCIVIL = 111
TRX_MODIFICAESTADOCIVIL = 112
TRX_BAJAESTADOCIVIL = 113
TRX_CONSULTAESTADOCIVIL = 114
TRX_NUEVOESTADO = 115
TRX_MODIFICAESTADO = 116
TRX_BAJAESTADO = 117
TRX_CONSULTAESTADO = 118
TRX_NUEVOESTRUCTURAIMP = 119
TRX_MODIFICAESTRUCTURAIMP = 120
TRX_BAJAESTRUCTURAIMP = 121
TRX_CONSULTAESTRUCTURAIMP = 122
TRX_NUEVOFORMAPAGO = 123
TRX_MODIFICAFORMAPAGO = 124
TRX_BAJAFORMAPAGO = 125
TRX_CONSULTAFORMAPAGO = 126
TRX_NUEVOGRADOESTUDIO = 127
TRX_MODIFICAGRADOESTUDIO = 128
TRX_BAJAGRADOESTUDIO = 129
TRX_CONSULTAGRADOESTUDIO = 130
TRX_NUEVOLOCALIDAD = 131
TRX_MODIFICALOCALIDAD = 132
TRX_BAJALOCALIDAD = 133
TRX_CONSULTALOCALIDAD = 134
TRX_NUEVOMONEDA = 135
TRX_MODIFICAMONEDA = 136
TRX_BAJAMONEDA = 137
TRX_CONSULTAMONEDA = 138
TRX_NUEVOMUNICIPIO = 139
TRX_MODIFICAMUNICIPIO = 140
TRX_BAJAMUNICIPIO = 141
TRX_CONSULTAMUNICIPIO = 142
TRX_NUEVOOCUPACIONES = 143
TRX_MODIFICAOCUPACIONES = 144
TRX_BAJAOCUPACIONES = 145
TRX_CONSULTAOCUPACIONES = 146
TRX_NUEVOPAIS = 147
TRX_MODIFICAPAIS = 148
TRX_BAJAPAIS = 149
TRX_CONSULTAPAIS = 150
TRX_NUEVOPOSICIONGLOBAL = 151
TRX_MODIFICAPOSICIONGLOBAL = 152
TRX_BAJAPOSICIONGLOBAL = 153
TRX_CONSULTAPOSICIONGLOBAL = 154
TRX_NUEVOPRODUCTO = 155
TRX_MODIFICAPRODUCTO = 156
TRX_BAJAPRODUCTO = 157
TRX_CONSULTAPRODUCTO = 158
TRX_NUEVOPROFESION = 159
TRX_MODIFICAPROFESION = 160
TRX_BAJAPROFESION = 161
TRX_CONSULTAPROFESION = 162
TRX_NUEVOPUESTO = 163
TRX_MODIFICAPUESTO = 164
TRX_BAJAPUESTO = 165
TRX_CONSULTAPUESTO = 166
TRX_NUEVORECEPPAGO = 167
TRX_MODIFICARECEPPAGO = 168
TRX_BAJARECEPPAGO = 169
TRX_CONSULTARECEPPAGO = 170
TRX_NUEVOREGION = 171
TRX_MODIFICAREGION = 172
TRX_BAJAREGION = 173
TRX_CONSULTAREGION = 174
TRX_NUEVOSUCURSAL = 175
TRX_MODIFICASUCURSAL = 176
TRX_BAJASUCURSAL = 177
TRX_CONSULTASUCURSAL = 178
TRX_NUEVOTIPOCAMBIO = 179
TRX_MODIFICATIPOCAMBIO = 180
TRX_BAJATIPOCAMBIO = 181
TRX_CONSULTATIPOCAMBIO = 182
TRX_NUEVOTIPOCLIENTE = 183
TRX_MODIFICATIPOCLIENTE = 184
TRX_BAJATIPOCLIENTE = 185
TRX_CONSULTATIPOCLIENTE = 186
TRX_NUEVOTIPOPRODUCTO = 187
TRX_MODIFICATIPOPRODUCTO = 188
TRX_BAJATIPOPRODUCTO = 189
TRX_CONSULTATIPOPRODUCTO = 190
TRX_NUEVOTIPOTELEFONO = 191
TRX_MODIFICATIPOTELEFONO = 192
TRX_BAJATIPOTELEFONO = 193
TRX_CONSULTATIPOTELEFONO = 194
TRX_NUEVOZONA = 195
TRX_MODIFICAZONA = 196
TRX_BAJAZONA = 197
TRX_CONSULTAZONA 198
TRX_NUEVOESTATUS = 199
TRX_MODIFICAESTATUS = 200
TRX_BAJAESTATUS = 201
TRX_CONSULTAESTATUS = 202
WS_SEGURIDAD_ASP=http://192.168.56.102:8081/SeguridadASPWS/