# Log files location
#property.basePath = C:/D/Servers/wildfly-10.1.0.Final/standalone/log
#property.basePath = /opt/jboss/wildfly/standalone/log
property.basePath = /opt/wildfly-10.1.0.Final/standalone/log

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} {%X{myUuid}} [%t] %c{1} - %msg%n


# RollingFileAppender name, pattern, path and rollover policy
appender.rolling.type = RollingFile
appender.rolling.name = fileLogger
appender.rolling.fileName= ${basePath}/CeroAhorroWS/CeroAhorroWS.log
appender.rolling.filePattern= ${basePath}/CeroAhorroWS/CeroAhorroWS_%d{yyyyMMdd}.log.gz
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} {%X{myUuid}} %level [%t] [%l] - %msg%n
appender.rolling.policies.type = Policies

# RollingFileAppender rotation policy
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1
appender.rolling.policies.time.modulate = true
appender.rolling.strategy.type = DefaultRolloverStrategy

# Configure root log
rootLogger.level = info
rootLogger.appenderRef.rolling.ref = fileLogger
#rootLogger.appenderRef.stdout.ref=STDOUT