#Queries
usuarios.dao.get.id=SELECT usuario_id as usuarioId,usuario FROM usuarios u WHERE u.usuario_id = ?
consSpei.dao.get.mov=SELECT sp.id_spei_outgoing as idSpei,sp.fh_operacion as fechaOperacion ,sp.clave_rastreo as claveRastreo \
        ,sp.status_operacion as statusOperacion,sp.cuenta_ordenante as cuentaOrigen,sorigen.descripcion as bancoOrigen \
        ,sp.cuenta_beneficiario as cuentaBeneficiario, sdestino.descripcion as bancoDestino,sp.monto \
    FROM spei_outgoing sp \
        JOIN spei_instituciones sdestino ON sp.id_institucion_ben = sdestino.id_institucion \
        JOIN spei_instituciones sorigen ON 90659 = sorigen.id_institucion  \
    WHERE sp.cuenta_ordenante=:cuentaOrd and sp.monto=:monto and sp.fecha_captura<=CURRENT_TIMESTAMP \
        and sp.cuenta_beneficiario=:cuentaBen  \
    ORDER BY sp.id_spei_outgoing DESC  \
    LIMIT 1
msgRee.dao.get.all=SELECT nc.clave,nc.nombre from nucleocentral.nctiporeenvios nc WHERE COALESCE(nc.activo,true) = true
msgRee.dao.get.clave=SELECT nc.id,nc.clave,nc.nombre,nc.activo from nucleocentral.nctiporeenvios nc WHERE nc.clave = :clave
valcorreo.dao.get.correo=select id, correo, estado,rfc,curp,token from plasticos.plvalidacion_correo  pl \
        WHERE pl.correo = :correo and pl.estado = :estado \
    ORDER BY pl.id DESC \
        LIMIT 1
app.dao.ins.bitacora=INSERT INTO ahorro.ahauditoria_consumo_ws(ncaplicativo_id,recurso,ip_origen,request,response,usuario_creacion) \
    VALUES(:ncaplicativoId,:recurso,:ipOrigen,:request,:response,:usuarioCreacion)
app.dao.ins.historico=SELECT ahorro.ahauditoria_ws_historico(:fecha)
app.dao.get.clave=SELECT nc.id,nc.clave,nc.nombre FROM  nucleocentral.ncaplicativo nc WHERE nc.clave=:clave
empresa.dao.get=SELECT id, clave_empresa, nombre_corto FROM plasticos.plempresas
tarjetas.dao.get.listado=SELECT * FROM (SELECT pp.pan, COALESCE(a.descripcion, pe.descripcion) AS estatus, \
    'FISICA' AS tipo_tarjeta,ah.cuenta,pp.plempresa_id,pl.clave_empresa,pl.nombre_corto,pl.id as empresaId \
    FROM plasticos.pladministracion_pan pp JOIN plasticos.plestatus_pan pe ON pp.estatus_id = pe.id \
        LEFT JOIN plasticos.plproveedores pv ON pp.proveedor_id = pv.proveedor_id \
        LEFT JOIN plasticos.plcuenta_pan pc ON pp.id = pc.pan_id \
        LEFT JOIN ahorro.ahestatus a ON	pc.estatus_id = a.id \
        LEFT JOIN ahorro.ahcuentas ah ON pc.cuenta_id = ah.id  \
        left join plasticos.plempresas pl on  pp.plempresa_id = pl.id \
    WHERE COALESCE(pv.nombre,'') = 'MASTERCARD-CACAO' \
    union \
    SELECT pt.numero_tarjeta AS pan, \
    ps.descripcion AS estatus,'VIRTUAL' AS tipo_tarjeta,ah.cuenta,pt.plempresa_id,pl.clave_empresa,pl.nombre_corto,pl.id as empresaId \
    FROM plasticos.pladministracion_tarjetas pt \
        LEFT JOIN plasticos.plproveedores pv ON pt.proveedor_id = pv.proveedor_id \
        JOIN plasticos.plestatus_tarjetas ps ON pt.estatus_tarjetas_id = ps.estatus_tarjetas_id \
        JOIN ahorro.ahcuentas ah ON	ah.id = pt.id_cuenta \
        left join plasticos.plempresas pl on  pt.plempresa_id = pl.id \
    WHERE COALESCE(pv.nombre,'') = 'MASTERCARD-CACAO' \
    ORDER BY 4) AS T1 \
  WHERE T1.empresaId= :empresaId
codi.dao.operaciones.cobro=SELECT * FROM ( \
    SELECT pg.cuenta_cobro_vendedor as cuentaVendedor,pg.cuenta_comprador as cuentaComprador, \
        pg.fecha_creacion as fechaProcesamiento, \
          pg.monto,ec.estatus,pg.folio,pg.folio_cobro_procesado as folioFinal,pg.referencia,\
            pg.institucion_vendedor as bancoDestino,pg.institucion_comprador as bancoOrigen \
    FROM codi.cobros_generados pg \
        LEFT JOIN codi.estatus_pagos ec ON pg.estatus_cobro_id = ec.id \
    WHERE pg.cuenta_vendedor = :cuenta or pg.cuenta_cobro_vendedor  = :cuenta \
    ) AS T1 \
    WHERE CAST(T1.fechaProcesamiento AS DATE) BETWEEN CAST(:fechaInicio AS DATE) AND CAST(:fechaFin AS DATE)
codi,dao.operaciones.pago=SELECT * FROM ( \
    SELECT pg.cuenta_pago_comprador as cuentaComprador,pg.cuenta_cobro_vendedor as cuentaVendedor, \
    pg.fecha_creacion as fechaProcesamiento,pg.monto,ec.estatus,pg.folio as folio,\
    pg.folio_final as folioFinal,pg.referencia, \
    pg.clave_institucion_vendedor as bancoDestino,pg.clave_institucion_comprador as bancoOrigen \
    FROM codi.pagos_generados pg \
        LEFT JOIN codi.estatus_pagos ec ON pg.estatus_pago_id = ec.id \
        WHERE pg.cuenta_comprador = :cuenta or pg.cuenta_pago_comprador  = :cuenta \
    ) AS T1 \
    WHERE CAST(T1.fechaProcesamiento AS DATE) BETWEEN CAST(:fechaInicio AS DATE) AND CAST(:fechaFin AS DATE)
codi.dao.operacion.cobro.referencia=SELECT * FROM ( \
    SELECT pg.cuenta_cobro_vendedor as cuentaVendedor,pg.cuenta_comprador as cuentaComprador, \
        pg.fecha_creacion as fechaProcesamiento, \
          pg.monto,ec.estatus,pg.folio,pg.folio_cobro_procesado as folioFinal,pg.referencia, \
          pg.institucion_vendedor as bancoDestino,pg.institucion_comprador as bancoOrigen \
    FROM codi.cobros_generados pg \
        LEFT JOIN codi.estatus_pagos ec ON pg.estatus_cobro_id = ec.id \
    ) AS T1 \
    WHERE CAST(T1.fechaProcesamiento AS DATE) BETWEEN CAST(:fechaInicio AS DATE) AND CAST(:fechaFin AS DATE) \
     AND (COALESCE(T1.folio,'')=:referencia or COALESCE(T1.folioFinal,'')=:referencia OR COALESCE(T1.referencia,'')=:referencia)
codi.dao.operacion.pago.referencia=SELECT * FROM ( \
    SELECT pg.cuenta_pago_comprador as cuentaComprador,pg.cuenta_cobro_vendedor as cuentaVendedor, \
    pg.fecha_creacion as fechaProcesamiento,pg.monto,ec.estatus,pg.folio as folio,\
    pg.folio_final as folioFinal,pg.referencia, \
    pg.clave_institucion_vendedor as bancoDestino,pg.clave_institucion_comprador as bancoOrigen \
    FROM codi.pagos_generados pg \
        LEFT JOIN codi.estatus_pagos ec ON pg.estatus_pago_id = ec.id \
    ) AS T1 \
    WHERE CAST(T1.fechaProcesamiento AS DATE) BETWEEN CAST(:fechaInicio AS DATE) AND CAST(:fechaFin AS DATE) \
        AND (COALESCE(T1.folio,'')=:referencia or COALESCE(T1.folioFinal,'')=:referencia OR COALESCE(T1.referencia,'')=:referencia)
spei.dao.catalogo.institucion=select sp.id_institucion as idInstitucion,sp.descripcion as nombre from spei_instituciones sp where sp.id_institucion = CAST(:idInstitucion AS INTEGER)
seestatus.dao.get.por-nombre=select se.* from seguridad.seestatus se where se.nombre=:nombre
seautenticado.dao.get.sesiones-activas=SELECT sa.id,nc.nombre as aplicativo,TO_CHAR(sa.fecha_creacion,'YYYY-MM-DD HH24:MI:SS') as fecha_creacion,se.nombre as estatus FROM seguridad.seautenticado sa \
   join seguridad.seestatus se on sa.id_estatus = se.id \
   join nucleocentral.ncaplicativo nc on nc.id=sa.id_aplicativo \
  where sa.usuario=:usuario and se.id=:idEstatus and nc.id=:idAplicativo
seautenticado.dao.update.sesiones-activas=UPDATE seguridad.seautenticado se SET id_estatus=:idEstatus,\
        fecha_modificacion=CURRENT_TIMESTAMP,usuario_modificacion=:usuarioModificacion \
     WHERE se.usuario=:usuario and se.id_estatus<>:idEstatus and se.id_aplicativo=:idAplicativo