package net.cero.ahorro.spei.enviospei.nuevospeicero;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2020-10-14T09:16:20.155-06:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://nuevoSpeiCero.spei.ws.izel.net/", name = "NuevoSpeiCeroIfz")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NuevoSpeiCeroIfz {

    @WebMethod
    @WebResult(name = "NuevoSpeiCeroResponse", targetNamespace = "http://nuevoSpeiCero.spei.ws.izel.net/", partName = "parameters")
    public NuevoSpeiCeroResponse procesar(
        @WebParam(partName = "parameters", name = "NuevoSpeiCeroRequest", targetNamespace = "http://nuevoSpeiCero.spei.ws.izel.net/")
        NuevoSpeiCeroRequest parameters
    );
}
