package net.cero.ahorro.spei.enviospei.nuevospeicero;

import org.apache.logging.log4j.LogManager;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2020-10-14T09:16:20.183-06:00
 * Generated source version: 2.4.6
 *
 */
@WebServiceClient(name = "NuevoSpeiCeroIfzService",
        wsdlLocation = "http://localhost:21080/SpeiOutgoing_WS/spei/v1/nuevo-spei-cero?wsdl",
        targetNamespace = "http://nuevoSpeiCero.spei.ws.izel.net/")
public class NuevoSpeiCeroIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://nuevoSpeiCero.spei.ws.izel.net/", "NuevoSpeiCeroIfzService");
    public final static QName NuevoSpeiCeroIfzPort = new QName("http://nuevoSpeiCero.spei.ws.izel.net/", "NuevoSpeiCeroIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:21080/SpeiOutgoing_WS/spei/v1/nuevo-spei-cero?wsdl");
        } catch (MalformedURLException e) {
            LogManager.getLogger(NuevoSpeiCeroIfzService.class.getName())
                    .info(
                            "Can not initialize the default wsdl from {0}", "http://localhost:21080/SpeiOutgoing_WS/spei/v1/nuevo-spei-cero?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NuevoSpeiCeroIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NuevoSpeiCeroIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NuevoSpeiCeroIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NuevoSpeiCeroIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NuevoSpeiCeroIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NuevoSpeiCeroIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NuevoSpeiCeroIfz
     */
    @WebEndpoint(name = "NuevoSpeiCeroIfzPort")
    public NuevoSpeiCeroIfz getNuevoSpeiCeroIfzPort() {
        return super.getPort(NuevoSpeiCeroIfzPort, NuevoSpeiCeroIfz.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NuevoSpeiCeroIfz
     */
    @WebEndpoint(name = "NuevoSpeiCeroIfzPort")
    public NuevoSpeiCeroIfz getNuevoSpeiCeroIfzPort(WebServiceFeature... features) {
        return super.getPort(NuevoSpeiCeroIfzPort, NuevoSpeiCeroIfz.class, features);
    }

}
