#Credenciales para consumir este microservicio
security.user.name=aspP4g0
security.user.password=a$pP4g04p1
#Credenciales para consumir ms asp-pago-onb
asp.pago.onb.user=aspP4g0
asp.pago.onb.pass=a$pP4g00n6
#Credenciales para consumir ms asp-pago-access
asp.pago.access.user=aspP4g0
asp.pago.access.pass=a$pP4g04cc3$$
#Credenciales para consumir ms asp-pago-management
asp.pago.management.user=aspP4g0
asp.pago.management.pass=a$pP4g0m4n463m3n7
#Credenciales para consumir ms asp-pago-notification
asp.pago.notification.user=aspP4g0
asp.pago.notification.pass=a$pP4g0n071f1c4710n
#Credenciales para consumir ms asp-pago-documents
asp.pago.documents.user=aspP4g0
asp.pago.documents.pass=a$pP4g0d0cum3n7$
#Credenciales para consumir ms asp-pago-payments
asp.pago.payments.user=aspP4g0
asp.pago.payments.pass=a$pP4g0p4ym3n7$
#Credenciales para consumir ms asp-pago-payments
asp.pago.codi.user=aspP4g0
asp.pago.codi.pass=a$pP4g0c0d1
#Credenciales para consumir ms asp-pago-jwt
asp.pago.jwt.user=aspJw7P4g0
asp.pago.jwt.pass=a$pP4g070K3NJW7
#Credenciales para consumir ms asp-pago-services-v2
asp.pago.services.user=ASP
asp.pago.services.pass=a5p*2o2A$
#Credenciales para consumir ms asp-pago-investments
asp.pago.investments.user=aspP4g0
asp.pago.investments.pass=a$pP4g01Nv3$7m3N7
#Credenciales para consumir ms admin-plasticos-services
admin.plasticos.services.user=ASP
admin.plasticos.services.pass=a5p2017$
login.services.usuario=A506B23F1086212AA000B46DFD45518A
login.services.password=A28F5B852414F9402782F091E5EF8666

#Credenciales para consumir ms ventanilla f�cil
ventanilla.facil.user=ASP
ventanilla.facil.pass=a5p2017$

#Llaves de cifrado
aes.key.password=0G$K5w%7YV8Xp7H
aes.key.general=0okDE3a+#
aes.key.cambio.pass=47FUksKs
aes.key.initial=YIIp&369#

#Token interno para consumir /api/storage de asp-pago-documents
security.storage.token=eb89844bdc6e461c9394693b752645f3dda40f9f7e0be08f8332a0d25a5810a8