#Version del logIn Asp Pago
path.login.version=logInV2
#Habilitar/Deshabilitar validacion mediante JWT
valida.jwt.token=true
#Path de los servicios de cambio de contrasena ASP PAGO
path.pwd.reset=password-reset
#Path api storage
path.api.storage=/onb/storage/