#MS asp-pago-onb
ms.onb.host=http://172.17.7.164
ms.onb.port=8014
#endpoints asp-pago-onb
ms.onb.registro.cuenta.simplificada=asp-pago-onb/registroDeCuentaSimplificada
ms.onb.validacion.correo=asp-pago-onb/validacionDeCorreo
ms.onb.alta.beneficiarios.V2=asp-pago-onb/altaBeneficiariosV2
ms.onb.valida.foto.ine=asp-pago-onb/validaFotoIne

#MS asp-pago-access
ms.access.host=http://172.17.7.164
ms.access.port=8015
#endpoints asp-pago-access
ms.access.peticion.cambio.pass.v2=asp-pago-access/peticionCambioPassV2
ms.access.cambio.password.v2=asp-pago-access/cambioPasswordV2
ms.access.logIn=asp-pago-access/logInV2
ms.access.validar.codigo.autorizacion=asp-pago-access/validarCodigoAutorizacion
ms.access.cambiar.codigo.autorizacion=asp-pago-access/cambiarCodigoAutorizacion
ms.access.valida.version.app=asp-pago-access/validaVersionApp
ms.access.cierra.sesion=asp-pago-access/cierraSesion
ms.access.obtener.datos.iniciales=asp-pago-access/obtenerDatosInicialesV
ms.access.validar.token.cambio.pass=asp-pago-access/validarTokenCambioPass
ms.access.password.reset.request=asp-pago-access/password-reset/request
ms.access.password.reset.valida.otp=asp-pago-access/password-reset/valida-otp
ms.access.password.reset.change=asp-pago-access/password-reset/change

#MS asp-pago-management
ms.management.host=http://172.17.7.164
ms.management.port=8016
#endpoints asp-pago-management
ms.management.consultar.cp=asp-pago-management/consultarCP
ms.management.obtener.saldo.ahorro=asp-pago-management/obtenerSaldoAhorroSAV2
ms.management.consulta.domicilio=asp-pago-management/consultaDomicilio
ms.management.lista.servicios=asp-pago-management/listaServicios
ms.management.lista.recargas=asp-pago-management/listaRecargas
ms.management.enviar.codigo=asp-pago-management/enviarCodigo
ms.management.reenviar.codigo.correo=asp-pago-management/reenviarCodigoPorCorreo
ms.management.valida.telefono=asp-pago-management/validaTelefono
ms.management.obtener.favoritos.cuenta=asp-pago-management/obtenerFavoritosCuenta
ms.management.registra.favorito.V2=asp-pago-management/registraFavoritoV2
ms.management.eliminar.favorito=asp-pago-management/eliminarFavorito
ms.management.valida.beneficiario.detalle=asp-pago-management/validaBeneficiarioDetalle
ms.management.alta.beneficiario.detalle=asp-pago-management/altaBeneficiarioDetalle
ms.management.valida.curp.nubarium=asp-pago-management/validaCurpNub
ms.management.registrar.token.huella=asp-pago-management/registrarTokenHuella
ms.management.obtener.detalle.cuenta=asp-pago-management/obtenerDetalleCuenta
ms.management.obtener.creditos.cuenta=asp-pago-management/obtenerListaCreditos
ms.management.obtener.tarjetas.cuenta=asp-pago-management/obtenerTarjetas
ms.management.obtener.detalle.cuenta.destino=asp-pago-management/obtenerDetalleCuentaDestino
ms.management.valida.curp.cecoban=asp-pago-management/validaCurpCecoban
ms.management.genera.edo.mov=asp-pago-management/generaReporteEstadoMovimientosV2

#MS asp-pago-payments
ms.payments.host=http://172.17.7.164
ms.payments.port=8017
#endpoints asp-pago-payments
ms.payments.procesamiento.spei.simple.V3=asp-pago-payments/procesamientoSpeiSimpleV3
ms.payments.procesa=asp-pago-payments/procesa
ms.payments.generar.abono.eiyu=asp-pago-payments/generarAbono

#MS asp-pago-notification
ms.notification.host=http://172.17.7.164
ms.notification.port=8018
#endpoints asp-pago-notification
ms.notification.enviar.mail.service=asp-pago-notification/enviarEmail
ms.notification.enviar.mail.attachment.service=asp-pago-notification/enviarEmailAttachment
ms.notification.enviar.sms=asp-pago-notification/enviarSMS

#MS asp-pago-documents
ms.documents.host=http://172.17.7.164
ms.documents.port=8019
#endpoints asp-pago-documents
ms.documents.genera.doc.cta.simplificada=asp-pago-documents/generaDocumentacionCtaSimplificada
ms.documents.genera.anexo.detalle.beneficiario=asp-pago-documents/generaAnexoDetalleBeneficiario
ms.documents.registra.imagenes.cuenta.simplificada=asp-pago-documents/registroImagenesCuentaAhorroSimplificada
ms.documents.upload.files.biometria.asppago=asp-pago-documents/api/storage/biometria-asppago
ms.documents.onb.upload.files.biometria.asppago=asp-pago-documents/onb/storage/biometria-asppago
ms.documents.onb.obtener.datos.ocr=asp-pago-documents/onb/storage/obtenerDatosOcr

#MS asp-pago-jwt
ms.jwt.host=http://172.17.7.164
ms.jwt.port=8026
#endpoints asp-pago-jwt
ms.jwt.login.auth.service=asp-pago-jwt/login-auth
ms.jwt.refresh.token.service=asp-pago-jwt/refresh-token
ms.jwt.valida.jwt.service=asp-pago-jwt/validaJWTToken

#MS asp-pago-codi
ms.codi.host=http://172.17.7.164
ms.codi.port=8020
#endpoints asp-pago-codi
ms.codi.registro.inicial.V2=asp-pago-codi/registroInicialV2
ms.codi.registro.subsecuente.V2=asp-pago-codi/registroSubsecuenteV2
ms.codi.registra.app.por.omision.V2=asp-pago-codi/actualizaAppOmisionRegistroCodiV2
ms.codi.validacion.cuentas.V2=asp-pago-codi/registroCuentasCodiV2
ms.codi.procesamiento.pago.V2=asp-pago-codi/procesamientoPagoV2
ms.codi.registra.pago.generado.V2=asp-pago-codi/registraPagoGeneradoV2
ms.codi.consultar.estatus.codi=asp-pago-codi/consultarEstatusCoDi
ms.codi.consultar.operaciones.codi=asp-pago-codi/consultarOperacionesCoDi
ms.codi.obtener.referencia.serial.cobro.V2=asp-pago-codi/obtenerReferenciaSerialCobroV2
ms.codi.registra.cobro.generado.V2=asp-pago-codi/registraCobroGeneradoV2
ms.codi.registrar.bitacora.codi=asp-pago-codi/registrarBitacoraCodi
ms.codi.procesamiento.devolucion.V2=asp-pago-codi/procesamientoDevolucionV2

#MS asp-pago-services-v2
ms.asp.pago.services.host=http://172.17.7.164
ms.asp.pago.services.port=8021
#endpoints asp-pago-services-v2
ms.services.consultar.ocupaciones=asp-pago-services-v2/consultarOcupaciones
ms.services.consultar.actividades=asp-pago-services-v2/consultarActividades
ms.services.consultar.giros.by.actividad.id=asp-pago-services-v2/consultarGirosByActividadId
ms.services.consultar.objetivos=asp-pago-services-v2/consultarObjetivos
ms.services.consultar.ingresos.mensuales=asp-pago-services-v2/consultarIngresosMensuales
ms.services.consultar.frecuencia=asp-pago-services-v2/consultarFrecuencia
ms.services.consultar.ahorros.mensuales=asp-pago-services-v2/consultarAhorrosMensuales
ms.services.consultar.sesion.incode=asp-pago-services-v2/consultarSesionIncode
ms.services.actualizar.sesion.incode=asp-pago-services-v2/actualizarSesionIncode
ms.services.finalizar.sesion.incode=asp-pago-services-v2/finalizarSesionIncode
ms.services.guardar.sesion.incode=asp-pago-services-v2/guardarSesionIncode
ms.services.subir.nivel.cuenta.remota=asp-pago-services-v2/subirNivelCuentaRemota
ms.services.valida.curp.cuenta=asp-pago-services-v2/validaCurpCuenta
ms.services.guardar.formulario=asp-pago-services-v2/guardarFormulario
ms.services.finalizar.sesion.incode.manual=asp-pago-services-v2/finalizarSesionIncodeManual

#MS admin-plasticos-services
ms.admin.plasticos.services.host=http://172.17.7.183
ms.admin.plasticos.services.port=8080
#endpoints admin-plasticos-services
ms.admin.plasticos.services.consultar.tarjeta=admin-plasticos-services/consultar-tarjeta
ms.admin.plasticos.services.asignar.tarjeta.fisica=admin-plasticos-services/asignarTarjetaFisica
ms.admin.plasticos.services.bloquear.tarjeta=admin-plasticos-services/bloquear-tarjeta
ms.admin.plasticos.services.reasignar.tarjeta=admin-plasticos-services/reasignar-tarjeta
ms.admin.plasticos.services.asignar.otra.tarjeta=admin-plasticos-services/asignar-otra-tarjeta
ms.admin.plasticos.services.asignar.cuenta=admin-plasticos-services/asignar-cuenta
ms.admin.plasticos.services.solicitar.reposicion=admin-plasticos-services/solicitar-reposicion
ms.admin.plasticos.services.desbloquear.tarjeta=admin-plasticos-services/desbloquear-tarjeta
ms.admin.plasticos.services.consultar.detalle.movimiento=admin-plasticos-services/consultar-detalle-movimiento
ms.admin.plasticos.services.consultar.movimientos.tarjeta=admin-plasticos-services/consultar-movimientos-tarjeta
ms.admin.plasticos.services.consultar.movimientos.asp-pago=admin-plasticos-services/consultar-movimientos-asp-pago
ms.admin.plasticos.services.solicitar.tarjeta.fisica=admin-plasticos-logistics/solicitarTarjetaFisica
ms.admin.plasticos.services.vincular.tarjeta.fisica=admin-plasticos-logistics/vincularTarjetaFisica
ms.admin.plasticos.services.consultar.cp.entrega=admin-plasticos-logistics/consultarCPEntrega
ms.admin.plasticos.services.consultar.mi.solicitud.tf=admin-plasticos-logistics/consultarMiSolicitudTF
ms.admin.plasticos.services.solicitar.reposicion.tarjeta.fisica=admin-plasticos-logistics/solicitarReposicionTarjetaFisica
ms.admin.plasticos.services.consultar.cvv.dinamico=admin-plasticos-services/consultar-cvv-dinamico
ms.admin.plasticos.services.asignar.nip=admin-plasticos-services/asignar-nip

#MS asp-pago-investments
ms.investments.host=http://172.17.7.164
ms.investments.port=8024
ms.investments.obtener.modalidades=asp-pago-investments/obtenerModalidades
ms.investments.obtener.plazos.porcentajes=asp-pago-investments/obtenerPlazosPorcentajes
ms.investments.obtener.tipos.reinversiones=asp-pago-investments/obtenerTiposReinversiones
ms.investments.obtener.inversiones=asp-pago-investments/obtenerInversiones
ms.investments.obtener.detalle.inversion=asp-pago-investments/obtenerDetalleInversion
ms.investments.alta.cuenta.inversion=asp-pago-investments/altaCuentaInversion
ms.investments.obtener.movimientos.inversion=asp-pago-investments/obtenerMovimientosInversion
ms.investments.alta.reinversion=asp-pago-investments/altaReinversion
ms.investments.cancelar.reinversion=asp-pago-investments/cancelarReinversion
ms.investments.simular.inversion=asp-pago-investments/simularInversion
ms.investments.enviar.estado.cuenta=asp-pago-investments/enviarEstadoCuenta