spring.profiles.active=@spring.profiles.active@
spring.config.import=optional:classpath:conceptos/conceptos-${spring.profiles.active}.properties, \
                     optional:classpath:endpoints/endpoints-${spring.profiles.active}.properties
spring.application.name=asp-pago-api
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true