server.port=8013
server.servlet.contextPath=/asp-pago-api
logging.level.org.springframework.boot.autoconfigure=ERROR
spring.config.import=file:/app/config/credenciales/credenciales.properties, \
                     file:/app/config/jwtConfig/endpoints.yml, \
                     file:/app/config/jwtConfig/jwtConfig.properties, \
                     file:/app/config/UUID/uuid.properties, \
                     file:/app/config/UUID/suffixes.yml, \
                     file:/app/config/UUID/suffixes-canales.yml, \
                     file:/app/config/resources/banderas.yml, \
                     file:/app/config/resources/claveErrores.yml, \
                     file:/app/config/resources/configuracion.properties
