property.basePath = /app/logs

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
#appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%X{myUuid}] [%t] %c{1} - %msg%n
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%X{myUuid}] [%t] %C{1}.%M(%F:%L) - %msg%n
appender.console.layout.charset = UTF-8

# RollingFileAppender - Archivo de log principal y patrón de rotación
appender.rolling.type = RollingFile
appender.rolling.name = fileLogger
appender.rolling.fileName= ${basePath}/asp-pago-api.log
appender.rolling.filePattern= ${basePath}/asp-pago-api-%d{yyyy-MM-dd}-%i.log.gz
appender.rolling.layout.type = PatternLayout
#appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] [%l] {%X{myUuid}} - %msg%n
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] [%C{1}.%M(%F:%L)] [%X{myUuid}] - %msg%n
appender.rolling.layout.charset = UTF-8

# Políticas de rotación: por tamaño y por tiempo
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1
appender.rolling.policies.time.modulate = true

appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 100MB

# Estrategia de rollover para mantener los logs
#appender.rolling.strategy.type = DefaultRolloverStrategy
#appender.rolling.strategy.max = 30  # Mantiene hasta 30 archivos de log comprimidos antes de eliminar los más antiguos

# Configuración del logger raíz
rootLogger.level = info
rootLogger.appenderRef.rolling.ref = fileLogger
rootLogger.appenderRef.stdout.ref=STDOUT

# Log de HikariCP en nivel info
logger.hikari.name = com.zaxxer.hikari
logger.hikari.level = info
logger.hikari.additivity = false
logger.hikari.appenderRef.console.ref = STDOUT
logger.hikari.appenderRef.fileLogger.ref = fileLogger