package net.cero.ahorro.spei.generaclabe;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2018-10-18T17:08:15.872-06:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "GeneraClabeIfzService", 
                  wsdlLocation = "http://localhost:21081/esb/spei/genera-clabe?wsdl",
                  targetNamespace = "http://generaClabe.spei.ws.izel.net/") 
public class GeneraClabeIfzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://generaClabe.spei.ws.izel.net/", "GeneraClabeIfzService");
    public final static QName GeneraClabeIfzPort = new QName("http://generaClabe.spei.ws.izel.net/", "GeneraClabeIfzPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:21081/esb/spei/genera-clabe?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeneraClabeIfzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:21081/esb/spei/genera-clabe?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeneraClabeIfzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeneraClabeIfzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneraClabeIfzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GeneraClabeIfzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GeneraClabeIfzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GeneraClabeIfzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GeneraClabeIfz
     */
    @WebEndpoint(name = "GeneraClabeIfzPort")
    public GeneraClabeIfz getGeneraClabeIfzPort() {
        return super.getPort(GeneraClabeIfzPort, GeneraClabeIfz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneraClabeIfz
     */
    @WebEndpoint(name = "GeneraClabeIfzPort")
    public GeneraClabeIfz getGeneraClabeIfzPort(WebServiceFeature... features) {
        return super.getPort(GeneraClabeIfzPort, GeneraClabeIfz.class, features);
    }

}
