
package net.std.valida.nubarium;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidaNubariumService", targetNamespace = "http://valida.ws.net/", wsdlLocation = "http://sr-nubarium.integraopciones.mx:8081/ValidacionNubarium/ValidacionNubarium?wsdl")
public class ValidaNubariumService
    extends Service
{

    private final static URL VALIDANUBARIUMSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDANUBARIUMSERVICE_EXCEPTION;
    private final static QName VALIDANUBARIUMSERVICE_QNAME = new QName("http://valida.ws.net/", "ValidaNubariumService");
    private final static QName VALIDANUBARIUMSERVICECURP_QNAME = new QName("http://valida.ws.net/", "validaCurp");
    private final static QName VALIDANUBARIUMSERVICERFC_QNAME = new QName("http://valida.ws.net/", "validaRFC");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sr-nubarium.integraopciones.mx:8081/ValidacionNubarium/ValidacionNubarium?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDANUBARIUMSERVICE_WSDL_LOCATION = url;
        VALIDANUBARIUMSERVICE_EXCEPTION = e;
    }

    public ValidaNubariumService() {
        super(__getWsdlLocation(), VALIDANUBARIUMSERVICE_QNAME);
    }

    public ValidaNubariumService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDANUBARIUMSERVICE_QNAME, features);
    }

    public ValidaNubariumService(URL wsdlLocation) {
        super(wsdlLocation, VALIDANUBARIUMSERVICE_QNAME);
    }

    public ValidaNubariumService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDANUBARIUMSERVICE_QNAME, features);
    }

    public ValidaNubariumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidaNubariumService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidaNubarium
     */
    @WebEndpoint(name = "ValidaNubariumPort")
    public ValidaNubarium getValidaNubariumPort() {
        return super.getPort(new QName("http://valida.ws.net/", "ValidaNubariumPort"), ValidaNubarium.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidaNubarium
     */
    @WebEndpoint(name = "ValidaNubariumPort")
    public ValidaNubarium getValidaNubariumPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://valida.ws.net/", "ValidaNubariumPort"), ValidaNubarium.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDANUBARIUMSERVICE_EXCEPTION!= null) {
            throw VALIDANUBARIUMSERVICE_EXCEPTION;
        }
        return VALIDANUBARIUMSERVICE_WSDL_LOCATION;
    }

	public static QName getValidanubariumservicecurpQname() {
		return VALIDANUBARIUMSERVICECURP_QNAME;
	}

}
