
package net.std.valida.nubarium;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidaNubarium", targetNamespace = "http://valida.ws.net/")
public interface ValidaNubarium {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validaRFC", targetNamespace = "http://valida.ws.net/", className = "net.ws.valida.ValidaRFC")
    @ResponseWrapper(localName = "validaRFCResponse", targetNamespace = "http://valida.ws.net/", className = "net.ws.valida.ValidaRFCResponse")
    public String validaRFC(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validaCurp", targetNamespace = "http://valida.ws.net/", className = "net.ws.valida.ValidaCurp")
    @ResponseWrapper(localName = "validaCurpResponse", targetNamespace = "http://valida.ws.net/", className = "net.ws.valida.ValidaCurpResponse")
    public String validaCurp(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
