#MS asp-pago-notification
ms.notification.host=http://172.17.7.164
ms.notification.port=8018
#endpoints asp-pago-notification
ms.notification.enviar.mail.service=asp-pago-notification/enviarEmail
ms.notification.enviar.mail.attachment.service=asp-pago-notification/enviarEmailAttachment
ms.notification.enviar.sms.service=asp-pago-notification/enviarSMS

#MS asp-pago-management
ms.management.host=http://172.17.7.164
ms.management.port=8016
#endpoints asp-pago-management
ms.management.consulta.saldo.service=asp-pago-management/obtenerSaldoAhorroSAV2

#WS admin-plasticos-services
ws.admin.plasticos.services.host=http://172.17.7.183
ws.admin.plasticos.services.port=8080
#endpoints admin-plasticos-services
ws.fondear.tarjeta.orquestador.service=admin-plasticos-services/fondearTarjetaOrquestador
ws.retirar.tarjeta.orquestador.service=admin-plasticos-services/retirarTarjetaOrquestador