spring.cero.datasource.hikari.jdbc-url=${DB_CERO_HOST}?currentSchema=public&ApplicationName=procesaRendimientosCero
spring.cero.datasource.hikari.username=${DB_CERO_USER}
spring.cero.datasource.hikari.password=${DB_CERO_PASS}
spring.cero.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.cero.datasource.hikari.sql-script-encoding=UTF-8

spring.cero.datasource.hikari.pool-name=CeroPool
spring.cero.datasource.hikari.maximum-pool-size=5
spring.cero.datasource.hikari.connection-timeout=300000
spring.cero.datasource.hikari.minimum-idle=2
spring.cero.datasource.hikari.max-lifetime=120000

spring.procrea.datasource.hikari.jdbc-url=${DB_PROCREA_HOST}?currentSchema=public&ApplicationName=procesaRendimientosCero
spring.procrea.datasource.hikari.username=${DB_PROCREA_USER}
spring.procrea.datasource.hikari.password=${DB_PROCREA_PASS}
spring.procrea.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.procrea.datasource.hikari.sql-script-encoding=UTF-8

spring.procrea.datasource.hikari.pool-name=ProcreaPool
spring.procrea.datasource.hikari.maximum-pool-size=5
spring.procrea.datasource.hikari.connection-timeout=300000
spring.procrea.datasource.hikari.minimum-idle=2
spring.procrea.datasource.hikari.max-lifetime=120000