spring.profiles.active=@spring.profiles.active@
spring.config.import=classpath:conceptos/conceptos-${spring.profiles.active}.properties, \
                     classpath:endpoints/endpoints-${spring.profiles.active}.properties
spring.application.name=procesaRendimientosCero
spring.main.web-application-type=none