server.port=8027
logging.level.org.springframework.boot.autoconfigure=ERROR
spring.config.import=file:/app/config/db/database.properties, \
                     file:/app/config/credenciales/credenciales.properties, \
                     file:/app/config/UUID/uuid.properties, \
                     file:/app/config/scheduled/scheduledConfig.properties