package net.std.constantes;

import java.util.HashMap;

import org.springframework.http.HttpStatus;

import com.google.gson.Gson;

public class Errores { 

	public static final int SIN_ERROR = 0;
	public static final int ERROR_INESPERADO = 101;
	public static final int CAPTURE_CAMPOS_REQUERIDOS = 102;
	public static final int ERROR_INICIALIZACION_DATOS = 103;
	public static final int ERROR_SERVICIO_MULE = 104;
	public static final int ERROR_FIRMA_NO_VERIFICADA = 105;
	public static final int ERROR_FIRMA = 106;
	public static final int ERROR_LLAVE = 107;
	public static final int ERROR_PAGO = 108;
	public static final int ERROR_DATOS_CUENTA_NO_EXISTE = 109;
	public static final int ERROR_DATOS_SALDO = 110;
	public static final int ERROR_PARAMETROS = 111;
	public static final int ERROR_SALDO_INSUFICIENTE = 112;
	public static final int ERROR_CARGO_CUENTA = 113;
	public static final int ERROR_ABONO_CUENTA = 114;
	
	public static final int ERROR_MONTO = 115;
	public static final int ERROR_NOMBRE_ORDENANTE = 116;
	public static final int ERROR_CUENTA_ORDENANTE = 117;
	public static final int ERROR_NOMBRE_BENEFICIARIO = 118;
	public static final int ERROR_CUENTA_BENEFICIARIO = 119;
	
	public static final int ERROR_DEVOLUCION = 120;
	public static final int OK_DEVOLUCION = 121;
	public static final int ERROR_AVISO_PAGO_Std = 122;
	public static final int ERROR_AVISO_ESTADO_Std = 123;
	
	public static final int ERROR_INSTITUCION_ID = 124; 
	public static final int ERROR_TIPO_PAGO = 125;
	public static final int ERROR_TIPO_CUENTA_BENEFICIARIO = 126;
	public static final int ERROR_TIPO_CUENTA_ORDENANTE = 127;
	public static final int ERROR_AREA_EMITE = 128;
	public static final int ERROR_CLAVE_RASTREO = 129;
	public static final int ERROR_CONCEPTO_CANCELACION = 130; 
	public static final int ERROR_CANCELACION_TRANSFERENCIA = 131;
	public static final int ERROR_RFC_ORDENANTE = 132;
	public static final int ERROR_RFC_BENEFICIARIO = 133;
	
	public static final int ERROR_CAMPOS_REQUERIDOS = 134;
	public static final int ERROR_SIN_PERMISO = 135;
	public static final int ERROR_SIN_CONEXION_BD = 136;
	
	public static final int ERROR_CREAR_CUENTA = 150;
	public static final int ERROR_CREAR_CLABE = 151;
	public static final int ERROR_CREAR_REFERENCIA = 152;
	public static final int ERROR_CREAR_CUENTA_PLD = 153;
	public static final int ERROR_CREAR_CUENTA_CONCEPTOS = 154;
	public static final int ERROR_CUENTA_EJE_NO_EXISTE = 155;
	public static final int ERROR_CREAR_SOLICITANTE = 156;
	public static final int ERROR_CUENTA_NO_ACTIVA = 157;
	public static final int ERROR_PRODUCTO_NO_EXISTE = 158;
	
	public static final int ERROR_REGISTRO_CUENTAS_PLD = 159;
	public static final int ERROR_REGISTRO_MATRIZ_PLD = 160;
	public static final int ERROR_REGISTRO_POSICION_GLOBAL = 161;
	public static final int ERROR_CUENTA_BLU = 162;
	public static final int ERROR_CUENTA_FINAL = 163;
	public static final int ERROR_CUENTA_DESCONOCIDA = 164;
	public static final int ERROR_PERMISO = 165;
	
	public static final int ERROR_TIPO_DOCUMENTO = 166;
	public static final int ERROR_EXPEDIENTE = 167;
	public static final int ERROR_CUENTA_BLOQUEADA = 168;
	public static final int ERROR_CUENTA_PADRE_BLOQUEADA = 169;
	public static final int ERROR_CUENTA_SIN_CUENTA_PADRE = 170;
	public static final int ERROR_CUENTA_PARTICIPANTE_ASOCIADO = 171;
	public static final int ERROR_CUENTA_PARTICIPANTE_NO_EXISTE = 172;
	public static final int ERROR_CUENTA_PARTICIPANTE_MAL_IDENTIFICADA = 173;
	public static final int ERROR_BITACORA = 174;
	public static final int ERROR_CATALOGO = 175;
	public static final int ERROR_BITACORA_TRANSACCIONES = 176;
	public static final int ERROR_SOLICITANTE = 177;
	public static final int ERROR_AUTORIZAR = 178;
	
	public static final int ERROR_INSERTAR_TRANSACCION = 179;
	public static final int ERROR_SALDO_NO_ENCONTRADO = 180;
	public static final int ERROR_CUENTA = 181;
	public static final int ERROR_DEPOSITO = 182;
	public static final int ERROR_RETIRO = 183;
	public static final int ERROR_DEVOLUCION_DEPOSITO = 184;
	public static final int ERROR_DEVOLUCION_RETIRO = 185;
	public static final int ERROR_ROLLBACK = 186;
	public static final int ERROR_NUMERO_AUTORIZACION = 187;
	public static final int ERROR_CUENTA_VACIA = 188;
	public static final int ERROR_TRAFICO = 189;
	public static final int ERROR_CUENTA_NO_ACTIVADA = 190;
	public static final int ERROR_PRODUCTO_NO_CORRESPOND = 191;
	
	public static final int ERROR_INSERTAR_CUENTA_MASIVA = 192;
	public static final int ERROR_LEER_CUENTA_MASIVA = 193;
	public static final int ERROR_ACTUALIZAR_CUENTA_MASIVA = 194;
	
	public static final int ERROR_INSERTAR_CANAL = 195;
	public static final int ERROR_LEER_CANAL = 196;
	public static final int ERROR_ACTUALIZAR_CANAL = 197;
	
	public static final int ERROR_CUENTA_BLOQUEADA_POR_CANAL = 198;
	public static final int ERROR_CUENTA_BLOQUEADA_POR_CANAL_DEPENDIENTE = 199;
	
	public static final int ERROR_CUENTAS = 200;
	
	public static final int ERROR_REPRESENTANTE_LEGAL = 201;
	public static final int ERROR_ESTADO_CUENTA = 202;
	public static final int ERROR_VALIDAR_CUENTA= 203;
	
	public static final int ERROR_LEER_CUENTA_REFERENCIADA = 204;
	public static final int ERROR_LEER_CUENTA_REFERENCIADA_MASIVA = 205;
	public static final int ERROR_LISTAR_CUENTA_REFERENCIADA_MASIVA = 206;
	public static final int ERROR_INSERTAR_CUENTA_REFERENCIADA = 207;
	public static final int ERROR_INSERTAR_CUENTA_REFERENCIADA_MASIVA = 208;
	public static final int ERROR_ACTUALIZAR_CUENTA_REFERENCIADA_MASIVA = 209;
	public static final int ERROR_LEER_CUENTA_CLABE_IZEL = 210;
	public static final int ERROR_INSERTAR_CUENTA_CLABE_IZEL = 211;
	public static final int ERROR_ELIMINAR_CUENTA_REFERENCIADA_MASIVA = 212;
	public static final int ERROR_PROCESAR_CUENTA_REFERENCIADA_MASIVA = 213;
	public static final int ERROR_PROCESAR_LISTA_REFERENCIADA_MASIVA = 214;
	public static final int ERROR_CUENTA_REFERENCIADA_EXISTE = 215;
	public static final int ERROR_CUENTA_IZEL_REFERENCIADA_EXISTE = 216;
	public static final int ERROR_ALTA_CUENTA_REFERENCIADA_INCOMPLETA = 217;
	public static final int ERROR_LEER_TIPO_CUENTA_ID = 218;
	public static final int ERROR_ACCION_NO_DEFINIDA = 219;
	public static final int ERROR_LEER_CUENTA_CONCENTRADORA_REFERENCIADA = 220;
	
	
	public static final int ERROR_TIPO_CUENTA_ENTRADA = 221;
	public static final int ERROR_TIPO_CUENTA_SALIDA = 222;
	public static final int ERROR_TIPO_CUENTA_TRASPASO = 223;
	
	public static final int ERROR_LEER_PLAZAS = 224;
	public static final int ERROR_ACTUALIZAR_PLAZAS = 225;
	public static final int ERROR_LEER_PLAZAS_PROPIAS = 226;
	
	public static final int ERROR_BANCO_CUENTA_CLABE = 227;
	
	
	public static final int ERROR_SOLICITANTE_BLOQUEADO = 228;
	public static final int ERROR_INSERTAR_DATOS_CUENTA_REFERENCIADA = 229;
	public static final int ERROR_CUENTA_REFERENCIADA_EN_PROCESO = 230;
	
	
	/* CODIGOS SPEI -> Std */
	public static final int PENDIENTE = 3;
	public static final int RECHAZADO = 2;
	public static final int CANCELADO = 5;
	public static final int LIQUIDADO = 6;
	
	/* CODIGOS DE ERROR SERVICIOS REST */
	public static final int OK = HttpStatus.OK.value();
	public static final int CONTENIDO_PARCIAL = HttpStatus.PARTIAL_CONTENT.value();
	public static final int PETICION_INCORRECTA = HttpStatus.BAD_REQUEST.value();
	public static final int ERROR_INTERNO = HttpStatus.INTERNAL_SERVER_ERROR.value();
	
	
	private static HashMap<Integer, String> descError = new HashMap<Integer, String>();

	static {
		descError.put(ERROR_INESPERADO,"OCURRIO UN ERROR, CONSULTE CON EL SUPERVISOR DE AREA : %s");
		descError.put(CAPTURE_CAMPOS_REQUERIDOS,"CAMPO %s REQUERIDO");

		descError.put(SIN_ERROR,"SIN ERROR %s");
		descError.put(ERROR_INICIALIZACION_DATOS,"ERROR AL INICIALIZAR ACCESO A LOS DATOS %s");
		descError.put(ERROR_SERVICIO_MULE, "ERROR DE CONEXION CON SERVICIO SPEI %s");
		descError.put(ERROR_FIRMA_NO_VERIFICADA, "LA FIRMA NO SE HA PODIDO VERIFICAR %s");
		descError.put(ERROR_FIRMA, "ERROR AL OBTENER LA FIRMA DE ORIGEN %s");
		descError.put(ERROR_LLAVE, "ERROR AL OBTENER LA LLAVE DE ORIGEN %s");
		descError.put(ERROR_PAGO, "ERROR AL OBTENER EL CAMPO DE PAGO %s");
		descError.put(ERROR_DATOS_CUENTA_NO_EXISTE, "NO EXISTEN LOS DATOS DE LA CUENTA ASOCIADOS CON LA CUENTA CLABE %s");
		descError.put(ERROR_DATOS_SALDO, "NO SE PUDO OBTENER EL SALDO DE LA CUENTA, CONSULTE CON SU ADMINISTRADOR %s");
		descError.put(ERROR_PARAMETROS, "ERROR PARAMETRO : %s");
		descError.put(ERROR_SALDO_INSUFICIENTE, "SALDO INSUFICIENTE EN LA CUENTA CONCENTRADORA %s");
		descError.put(ERROR_CARGO_CUENTA, "ERROR AL PROCESAR EL CARGO A LA CUENTA CONCENTRADORA %s");
		descError.put(ERROR_ABONO_CUENTA, "ERROR AL PROCESAR EL ABONO A LA CUENTA CONCENTRADORA %s");
		
		descError.put(ERROR_MONTO, "ERROR EN EL MONTO DE LA OPERACION %s");
		descError.put(ERROR_NOMBRE_ORDENANTE, "ERROR EN EL NOMBRE DEL ORDENANTE %s");
		descError.put(ERROR_CUENTA_ORDENANTE, "ERROR EN LA CUENTA DEL ORDENANTE %s");
		descError.put(ERROR_NOMBRE_BENEFICIARIO, "ERROR EN EL NOMBRE DEL BENEFICIARIO %s");
		descError.put(ERROR_CUENTA_BENEFICIARIO, "ERROR EN LA CUENTA DEL BENEFICIARIO %s");
		
		descError.put(ERROR_AVISO_PAGO_Std, "ERROR AL DAR AVISO AL PARTICIPANTE Std DE UN ABONO A CUENTA %s");
		descError.put(ERROR_AVISO_ESTADO_Std, "ERROR AL DAR AVISO AL PARTICIPANTE Std DE UN CAMBIO DE ESTADO %s");
		
		descError.put(ERROR_DEVOLUCION, "ERROR EN LA DEVOLUCION DEL CARGO EFECTUADO EN LA CUENTA CONCENTRADORA, CONSULTE CON SU ADMINISTRADOR %s");
		descError.put(OK_DEVOLUCION, "DEVOLUCION CORRECTA A LA CUENTA CONCENTRADORA %s");
		
		descError.put(ERROR_INSTITUCION_ID, "ERROR AL OBTENER EL ID DE LA INSTITUCION DE LA CUENTA DEL BENEFICIARIO %s");
		descError.put(ERROR_TIPO_PAGO, "ERROR AL OBTENER EL TIPO DE PAGO %s");
		descError.put(ERROR_TIPO_CUENTA_BENEFICIARIO, "ERROR AL OBTENER EL TIPO DE CUENTA BENEFICIARIA %s");
		descError.put(ERROR_TIPO_CUENTA_ORDENANTE, "ERROR AL OBTENER EL TIPO DE CUANTA ORDENANTE %s");
		descError.put(ERROR_AREA_EMITE, "ERROR AL OBTENER EL AREA QUE EMITE %s");
		
		descError.put(ERROR_CLAVE_RASTREO, "ERROR AL OBTENER LA CLAVE DE RASTREO %s");
		descError.put(ERROR_CONCEPTO_CANCELACION, "ERROR AL OBTENER EL CONCEPTO DE CANCELACION DE LA TRANSFERENCIA POR PARTICIPANTE Std %s"); 
		descError.put(ERROR_CANCELACION_TRANSFERENCIA, "ERROR AL HACER LA DEVOLUCION DE LA CANCELACION DE LA TRANSFERENCIA %s");
		
		descError.put(ERROR_RFC_ORDENANTE, "ERROR AL OBTENER LA CLAVE DE RASTREO %s");
		descError.put(ERROR_RFC_BENEFICIARIO, "ERROR AL OBTENER LA CLAVE DE RASTREO %s");
		
			
		
		descError.put(PENDIENTE,"PENDIENTE DE LIQUIDAR %s");
		descError.put(RECHAZADO,"RECHAZADO %s");
		descError.put(CANCELADO,"CANCELADO %s");
		descError.put(LIQUIDADO,"LIQUIDADO %s");
	
		/*
		descError.put(PENDIENTE,"EL PAGO FUE ACEPTADO SIN ERRORES Y SERA ENVIADO A BANXICO");
		descError.put(RECHAZADO,"EL PAGO HA SIDO RECHAZADO POR PSPEI O BANXICO %s");
		descError.put(CANCELADO,"EL PAGO HA SIDO CANCELADO POR BANXICO %s");
		descError.put(LIQUIDADO,"EL PAGO FUE LIQUIDDO EXITOSAMENTE");
		*/
		
		descError.put(OK, "%s");
		descError.put(CONTENIDO_PARCIAL,"PARTIAL CONTENT %s");
		descError.put(PETICION_INCORRECTA,"BAD REQUEST %s");
		descError.put(ERROR_INTERNO,"INTERNAL SERVER ERROR %s");
		
		descError.put(ERROR_CAMPOS_REQUERIDOS,"CAMPO REQUERIDO %s");
		descError.put(ERROR_SIN_PERMISO,"NO CUENTA CON LOS PERMISOS SUFICIENTES %s");
		descError.put(ERROR_SIN_CONEXION_BD,"NO ES POSIBLE CONECTARSE CON LA FUENTE DE DATOS %s");
		
		descError.put(ERROR_CREAR_CUENTA,"NO FUE POSIBLE CREAR CUENTA %s");
		descError.put(ERROR_CREAR_CLABE,"NO FUE POSIBLE CREAR CUENTA INTERBANCARIA %s");
		descError.put(ERROR_CREAR_REFERENCIA,"NO FUE POSIBLE CREAR LA REFERENCIA %s");
		descError.put(ERROR_CREAR_CUENTA_PLD,"NO FUE POSIBLE CREAR CONCEPTOS PLD DE LA CUENTA %s");
		descError.put(ERROR_CREAR_CUENTA_CONCEPTOS,"NO FUE POSIBLE CREAR CONCEPTOS DE LA CUENTA %s");
		descError.put(ERROR_CUENTA_EJE_NO_EXISTE,"NO EXISTE LA CUENTA EJE EN AHORRO %s");
		descError.put(ERROR_CREAR_SOLICITANTE,"NO ES POSIBLE INGRESAR EL SOLICITANTE %s");
		descError.put(ERROR_CUENTA_NO_ACTIVA,"CUENTA NO ACTIVA, ESTATUS %s");
		descError.put(ERROR_PRODUCTO_NO_EXISTE,"PRODUCTO AHORRO NO EXISTE ó ESTA DESACTIVADO %s");
		
		descError.put(ERROR_REGISTRO_CUENTAS_PLD,"NO SE REGISTRO LOS DATOS DE PLD %s");
		descError.put(ERROR_REGISTRO_MATRIZ_PLD,"NO SE REGISTRO LOS DATOS DE MATRIZ DE RIESGO PLD %s");
		descError.put(ERROR_REGISTRO_POSICION_GLOBAL,"NO SE REGISTRO LOS DATOS DE CUENTA EN LA POSICION GLOBAL %s");
		descError.put(ERROR_CUENTA_BLU,"ERROR IDENTIFICADOR DE CUENTA NO ES CUENTA_BLU %s");
		descError.put(ERROR_CUENTA_FINAL,"ERROR IDENTIFICADOR DE CUENTA NO ES CUENTA_FINAL, SIN DEPENDENCIA %s");
		descError.put(ERROR_CUENTA_DESCONOCIDA,"ERROR TIPO DE CUENTA DESCONOCIDO %s");
		
		descError.put(ERROR_PERMISO,"NO TIENE PERMISOS PARA EFECTAR ESTE PROCESO %s");
		descError.put(ERROR_TIPO_DOCUMENTO,"NO EXISTE EL TIPO DE DOCUMENTO A CARGAR %s");
		descError.put(ERROR_EXPEDIENTE,"ERROR EN EL EXPEDIENTE %s");
		
		descError.put(ERROR_CUENTA_BLOQUEADA,"ERROR LA CUENTA ESTA BLOQUEADA %s");
		descError.put(ERROR_CUENTA_PADRE_BLOQUEADA,"ERROR LA CUENTA PADRE(PARTICIPANTE) ESTA BLOQUEADA %s");
		descError.put(ERROR_CUENTA_SIN_CUENTA_PADRE,"ERROR LA CUENTA FINAL NO ESTA ASOCIADA CON UNA CUENTA PADRE (PARTICIPANTE) %s");
		descError.put(ERROR_CUENTA_PARTICIPANTE_ASOCIADO,"ERROR LA CUENTA PARTICIPANTE TIENE ASOCIADO A OTRO ASOCIADO %s");
		
		descError.put(ERROR_CUENTA_PARTICIPANTE_NO_EXISTE,"ERROR LA CUENTA PARTICIPANTE NO EXISTE O NO ESTA VIGENTE %s");
		descError.put(ERROR_CUENTA_PARTICIPANTE_MAL_IDENTIFICADA,"ERROR LA CUENTA PARTICIPANTE MAL IDENTIFICADA %s");
		
		descError.put(ERROR_BITACORA,"ERROR AL INSERTAR LA INFORMACION EN LA BITACORA %s");
		descError.put(ERROR_CATALOGO,"ERROR AL OBTENER EL CATALOGO %s");
		
		descError.put(ERROR_BITACORA_TRANSACCIONES,"ERROR AL INSERTAR LA TRANSACCION EN LA BITACORA %s");
		descError.put(ERROR_SOLICITANTE,"SOLICITANTE NO ENCONTRADO O NO SE PUDO GENERAR NUEVO SOLICITANTE %s");
		descError.put(ERROR_AUTORIZAR,"ERROR AL AUTORIZAR LA TRANSACCION CON CLAVE DE RASTREO, %s POSIBLE NO EXISTE O YA ESTA PROCESADO");
		
		descError.put(ERROR_INSERTAR_TRANSACCION, "ERROR AL INSERTAR LA TRANSACCION CUENTA %s");
		descError.put(ERROR_SALDO_NO_ENCONTRADO, "NO SE ENCONTRO EL SALDO DE LA CUENTA %s");
		descError.put(ERROR_CUENTA, "NO SE OBTUVO DATOS DE LA CUENTA %s");
		
		
		descError.put(ERROR_DEPOSITO, "ERROR AL HACER EL DEPOSITO A LA CUENTA %s");
		descError.put(ERROR_RETIRO, "ERROR AL HACER EL RETIRO A LA CUENTA %s");
		descError.put(ERROR_DEVOLUCION_DEPOSITO, "ERROR AL HACER DEVOLICION DE DEPOSITO A LA CUENTA %s");
		descError.put(ERROR_DEVOLUCION_RETIRO, "ERROR AL HACER DEVOLUCION DE RETIRO A LA CUENTA %s");
		descError.put(ERROR_ROLLBACK, "NO SE REALIZO EL ROLL BACK DE LA AUTORIZACION %s");
		descError.put(ERROR_NUMERO_AUTORIZACION, "NO SE PUEDE OBTENER EL NUMERO DE AUTORIZACION");
		descError.put(ERROR_CUENTA_VACIA, "LA INFORMACION PROPORCIONADA PARA LA BUSQUEDA DE LA CUENTA ES INVALIDA %s");
		
		descError.put(ERROR_TRAFICO, "ERROR AL INSERTAR LA TRANSACCION DE ENTRADA Y SALIDA DE SPEIS (TRAFICO) %s");
		descError.put(ERROR_CUENTA_NO_ACTIVADA, "ERROR LA CUENTA TIENE ESTATUS DE NO ACTIVADO : %s");
		descError.put(ERROR_PRODUCTO_NO_CORRESPOND, "ERROR PRODUCTO PROPORCIONADO NO CORRESPONDE CON EL PRODUCTO DE LA CUENTA : %s");
		
		descError.put(ERROR_INSERTAR_CUENTA_MASIVA, "ERROR AL INSERTAR LA CUENTA %s");
		descError.put(ERROR_LEER_CUENTA_MASIVA, "ERROR AL LEER LA CUENTA  %s");
		descError.put(ERROR_ACTUALIZAR_CUENTA_MASIVA, "ERROR AL ACTUALIZAR LA CUENTA %s");
		
		descError.put(ERROR_INSERTAR_CANAL, "ERROR AL INSERTAR EL CANAL DE AUTORIZACION %s");
		descError.put(ERROR_LEER_CANAL, "ERROR AL LEER EL CANAL DE AUTORIZACION %s");
		descError.put(ERROR_ACTUALIZAR_CANAL, "ERROR AL ACTUALIZAR EL CANAL DE AUTORIZACION %s");
		
		descError.put(ERROR_CUENTA_BLOQUEADA_POR_CANAL, "ERROR, LA CUENTA ESTA BLOQUEADA A NIVEL DE CANAL %s");
		descError.put(ERROR_CUENTA_BLOQUEADA_POR_CANAL_DEPENDIENTE, "ERROR, LA CUENTA ASOCIADA ESTA BLOQUEADA A NIVEL DE CANAL %s");
		
		descError.put(ERROR_CUENTAS, "ERROR, AL OBTENER LAS CUENTAS ASOCIADAS AL PRODUCTO %s");
		
		descError.put(ERROR_REPRESENTANTE_LEGAL, "ERROR AL CREAR EL REPRESENTAN LEGAL DE LA CUENTA %s");
		
		descError.put(ERROR_ESTADO_CUENTA, "ERROR AL CAMBIAR EL ESTATUS DE LA CUENTA %s");
		descError.put(ERROR_VALIDAR_CUENTA, "ERROR AL VALIDAR LA CUENTA %s");
		
		descError.put(ERROR_LEER_CUENTA_REFERENCIADA, "ERROR LEER CUENTA REFERENCIADA %s");
		descError.put(ERROR_LEER_CUENTA_REFERENCIADA_MASIVA, "ERROR LEER CUENTA REFERENCIADA MASIVA %s");
		descError.put(ERROR_LISTAR_CUENTA_REFERENCIADA_MASIVA, "ERROR LISTAR CUENTAS REFERENCIADAS MASIVAS %s");
		descError.put(ERROR_INSERTAR_CUENTA_REFERENCIADA, "ERROR INSERTAR CUENTA REFERENCIADA %s");
		descError.put(ERROR_INSERTAR_CUENTA_REFERENCIADA_MASIVA, "INSERTAR CUENTA REFERENCIADA MASIVA %s");
		descError.put(ERROR_ACTUALIZAR_CUENTA_REFERENCIADA_MASIVA, "ERROR ACTUALIZAR CUENTA REFERENCIADA MASIVA %s");
		descError.put(ERROR_LEER_CUENTA_CLABE_IZEL, "ERROR LEER CUENTA CLABE IZEL %s");
		descError.put(ERROR_INSERTAR_CUENTA_CLABE_IZEL, "ERROR INSERTAR CUENTA CLABE IZEL %s");
		
		descError.put(ERROR_ELIMINAR_CUENTA_REFERENCIADA_MASIVA, "ERROR ELIMINAR CUENTAS MASIVAS REFERENCIADAS %s");
		descError.put(ERROR_PROCESAR_CUENTA_REFERENCIADA_MASIVA, "ERROR PROCESAR CUENTAS MASIVAS REFERENCIADAS %s");
		descError.put(ERROR_PROCESAR_LISTA_REFERENCIADA_MASIVA, "ERROR PROCESAR LISTA MASIVAS REFERENCIADAS %s");
		
		descError.put(ERROR_CUENTA_REFERENCIADA_EXISTE, "ERROR CUENTA REFERENCIADA YA EXISTE %s");
		descError.put(ERROR_CUENTA_IZEL_REFERENCIADA_EXISTE, "ERROR CUENTA REFERENCIADA YA EXISTE EN EL SISTEMA DE IZEL %s");
		descError.put(ERROR_ALTA_CUENTA_REFERENCIADA_INCOMPLETA, "ERROR CUENTA EN ESTATUS REGISTRADA PERO INCOMPLETA EN IZEL %s");
		
		descError.put(ERROR_LEER_TIPO_CUENTA_ID, "ERROR TIPO CUENTA NO EXISTE EN EL CATALOGO %s");
		descError.put(ERROR_ACCION_NO_DEFINIDA, "ERROR TIPO DE ACCION NO DEFINIDO %s");
		descError.put(ERROR_LEER_CUENTA_CONCENTRADORA_REFERENCIADA, "ERROR CUENTA NO VALIDA PARA LA TRANSACCION %s");
		
		descError.put(ERROR_TIPO_CUENTA_ENTRADA, "ERROR TIPO CUENTA NO ES VALIDA PARA ESTA TRANSACCION DE DEPOSITO %s");
		descError.put(ERROR_TIPO_CUENTA_SALIDA, "ERROR TIPO CUENTA NO ES VALIDA PARA ESTA TRANSACCION DE RETIRO %s");
		descError.put(ERROR_TIPO_CUENTA_TRASPASO, "ERROR TIPO CUENTA NO ES VALIDA PARA ESTA TRANSACCION DE DEPOSITO %s");
		
		descError.put(ERROR_LEER_PLAZAS, "ERROR LISTA PLAZAS %s");
		descError.put(ERROR_ACTUALIZAR_PLAZAS, "ERROR ACTUALIZAR PLAZA %s");
		descError.put(ERROR_LEER_PLAZAS_PROPIAS, "ERROR LISTA PLAZAS PROPIAS %s");
		
		descError.put(ERROR_BANCO_CUENTA_CLABE, "ERROR LEER BANCO CUENTA CLABE %s");
	

		descError.put(ERROR_SOLICITANTE_BLOQUEADO, "SU NOMBRE FIGURA EN LA 'LISTA DE PERSONAS BLOQUEADAS' MOTIVO POR EL CUAL NO SE PUEDE REALIZAR LA OPERACIÓN DE CONFORMIDAD AL ART. 124 DE LA LEY DE AHORRO Y CRÉDITO POPULAR.");
		descError.put(ERROR_INSERTAR_DATOS_CUENTA_REFERENCIADA, "ERROR AL INSERTAR DATOS DE LA CUENTA REFERENCIADA.");
		descError.put(ERROR_CUENTA_REFERENCIADA_EN_PROCESO, "ERROR CUENTA REFERENCIADA NO EXISTE O ESTA EN PROCESO");
	}
	
	public static String desc(Integer pos, Object ... args){
		return String.format(descError.get(pos), args == null || args.length == 0 ? "" : args[0]);
	}
	
	public static String descGson(Integer pos, Object ... args){
		Respuesta respuesta = new Respuesta(pos, String.format(descError.get(pos), args == null || args.length == 0 ? "" : args[0]), null);
		return new Gson().toJson(respuesta);
	}
	
	public static String descGson(Long pos, Object ... args){
		Respuesta respuesta = new Respuesta(pos.intValue(), String.format(descError.get(pos.intValue()), args == null || args.length == 0 ? "" : args[0]), null);
		return new Gson().toJson(respuesta);
	}
	
	public static String descSvc(Long pos, Object ... args){
		Respuesta respuesta = new Respuesta(pos.intValue(), String.format("%s", args == null || args.length == 0 ? "" : args[0]), null);
		return new Gson().toJson(respuesta);
	}
	
	
}


