#Credenciales para consumir ms asp-pago-notification
asp.pago.notification.user=aspP4g0
asp.pago.notification.pass=a$pP4g0n071f1c4710n
#Credenciales para consumir ms asp-pago-management
asp.pago.management.user=aspP4g0
asp.pago.management.pass=a$pP4g0m4n463m3n7
#Credenciales para consumir ws admin-plasticos-services
admin.plasticos.services.user=ASP
admin.plasticos.services.pass=a5p2017$