#**********************************************
# LINKS A LOS SERVICIOS CONSUMIDOS
# FECHA : 
#**********************************************

PLASTICOS_WS=http://sr-ahorrows.integraopciones.mx:8081/AhorroCeroWS/rest
AHORRO_WS=http://sr-ahorrows.integraopciones.mx:8081/AhorroCeroWS/rest
SWITCHER_WS=http://sr-ahorrows.integraopciones.mx:8081/AhorroSwitchCeroWS/rest
SIMPLIFICADA_WS=http://sr-ahorrows.integraopciones.mx:8081/AhorroSimplificadaCeroWS/rest
CREDITO_WS = http://sr-servicios.integraopciones.mx:8081/CreditoWS/rest
ADMIN_SEG_WS = http://sr-adminseg.integraopciones.mx:8081/AdminSegWS/rest
SERVICIO_STD_WS=http://sr-blustdws.integraopciones.mx:8081/ServiciosSTD_WS/rest
NUCLEO_CARTERA_WS=http://sr-nucleocentralcartera.integraopciones.mx:8081/NucleoCentralCarteraWS/rest
ALFRESCO_WS = http://sr-alfrescows.integraopciones.mx:8081/WSAlfrescoREST/data


RUTA_ALFRESCO = /Alfresco/?folder/?archivo
CARPETA_ALFRESCO = Personas/%s/Ahorro/%s

#DATOS ENVIADOS A MULE_WSSTI  - usuario CODI
SECRET_KEY = 61PwZfSd1TTLkVPnBPM0Ww==

#URL SERVICIOS PRODUCCION
SERVICIO_BLU_WS = http://sr-vpnblu.integraopciones.mx:8081

USER_Std = aspfina
PASS_Std = password

#SERVICIOS DE PSpei_WS
REST_LOGIN = login
REST_NOTIFICAR_ESTADO = pspei/cambia_estado
REST_NOTIFICAR_ABONO = pspei/notificarIngreso
REST_CAMBIAR_CONTRASENA = pspei/cambiar_contrasena
REST_FECHA_OPERACION = pspei/fecha_operacion
REST_CIERRE_OPERACION = pspei/cierre_operacion
REST_INICIO_OPERACION = pspei/inicio_operacion

#CERTIFICADOS PRODUCCION

LLAVE_PUBLICA_BLU = /opt/wildfly-10.1.0.Final/portal/certificadosblu/llavePublicaBlu.crt
LLAVE_PUBLICA_ASP = /opt/wildfly-10.1.0.Final/portal/certificadosblu/90659.cer
LLAVE_PRIVADA_ASP = /opt/wildfly-10.1.0.Final/portal/certificadosblu/90659.key
ENCRIPTADO_LOCAL = 0


#CREDENCIALES SFTP PRODU
SFTP_USER = blu
SFTP_PASS = $s9d2ycNze!
SFTP_PORT = 31452
SFTP_HOST = 172.17.8.22
SFTP_RUTA = archivos/


PASSWORD_ASP = 12345678a

BYPASS = 1

#VERSIONADO
#VERSION =
VERSION = v1
PREFIJO = api


#SERVICIOS MULE WSSPEI
MULE_WS = sr-mule.integraopciones.mx
MULE_WSSPEI = sr-mule-sti.integraopciones.mx

#SERVICIOS_SISCOOP=sr-mule.integraopciones.mx
SERVICIOS_SISCOOP=sr-mule-plasticos.integraopciones.mx

#MULE_WS = 172.17.5.6
#MULE_WSSPEI = 172.17.5.6


#CUENTAS PARAMETROS
TIPO_CUENTA = CLABE
TIPO_PAGO = TERCERO A TERCERO
TIPO_AREA = Std
IVA = 0.00
TIPO_OPERACION = 0

#TIPOS REFERENCIAS
TIPO_REFERENCIA_BLU = 2
TIPO_REFERENCIA = 2

#PRODUCTOS
CNBV_ID	= 1
TIPO_AHORRO_ID = 1

#DATO CREACION DE CUENTA
PALABRAUSU = ASP
PALABRAHID = a5p2017$

USUARIO_ID = 10009
EMPRESA_ID = 1
SUCURSAL_ID = 1
HOST_ID = 127.0.0.1
UBICACION_ID = 1
AGENTE_ID = MOD-LAPAZ-OPC
OBTENER_CLABE_ID = 1
APLICACION_ID = BLU
APLICACION_CERO_ID = AHT
TABLA_CORRELATIVO = net.izel.model.spei.datos.Cuentas

CANAL_ID = 1
MONEDA_ID = PESOS
PRODUCTO_AHORRO = DEBITO

RENDIMIENTO = 0.00
GAT_NOMINAL = 0.00
GAT_REAL = 0.00
MONTO_APERTURA = 0.00
ASESOR_ID = 9
COMO_ENTERO_ID = 13
COMO_ENTERO_OBS = OTROS

#TIPO DE MOVIMIENTOS AHORRO PROCREA
ID_SPEI_DEVOLUCION_PR = 37

ESTATUS_CUENTA_ACTIVA = VIG
ESTATUS_CUENTA_CANCELADA = CANC 
ESTATUS_CUENTA_BLOQUEDA = BLOQ
ESTATUS_CUENTA_SEGUIMIENTO = SEG

ALTA_ID = ALTA
BAJA_ID = BAJA
TRAMITE_ID = TRAMITE

PRODUCTO = LINEA_BLU
PRODUCTO_PARTICIPANTE = LINEA_BLU_FINAL

#PROCESOS
PROCESO = PROCESOS_BLU_SPEI

#PERMISOS

TRX_CREAR_CUENTAS_AHORRO = 1
TRX_CREAR_PRODUCTOS_AHORRO = 2
TRX_CREAR_CONCEPTOS_AHORRO = 3
TRX_RETIRO_AHORRO = 4
TRX_DEPOSITO_AHORRO = 5
TRX_SALDO_AHORRO = 6
TRX_DEVOLUCION_AHORRO = 7
TRX_CREAR_CLABE = 8

TRX_LEER_DOCUMENTOS = 9
TRX_CREAR_EXPEDIENTE = 10
TRX_ACTUALIZAR_EXPEDIENTE = 11

TRX_LEER_CATALOGOS = 12
TRX_LEER_CUENTAS = 13

TRX_LEER_EXPEDIENTE 14
TRX_CAMBIO_ESTADO_CUENTA 15

TRX_NOTIFICACIONES 16
TRX_MENSAJERIA 17

TRX_CANCELAR_CUENTAS_AHORRO = 18

TRX_CREAR_CUENTAS_REFERENCIADAS = 19

#TRANSACCIONES PERMITIDAS
TRX_CUENTA_BLU = TRX_CUENTA_BLU
TRX_CUENTA_FINAL = TRX_CUENTA_FINAL

APLICATIVO_BLU = LINEA_BLU
APLICATIVO_BLU_FINAL = LINEA_BLU_FINAL

TRX_CUENTAS_AHORRO = TRX_CUENTAS_AHORRO
APLICATIVO_AHORRO = AHORRO

#DATOS POR DEFAULT DE PLD
PLD_INGRESO_MENSUAL = 6000.00
PLD_MONTO_MAXIMO_AHORRO = 6000.00
PLD_PUESTO = PUESTO_GENERAL

MR_ACT_CLAVE = 0000
MR_ACT_DESCRIPCION = ACTIVIDAD_GENERALES
MR_ACT_PONDERACION = 10

MR_GIR_CLAVE = 0000
MR_GIR_DESCRIPCION = GIRO_GENERALES
MR_GIR_PONDERACION = 10

MR_DES_CLAVE = 0000
MR_DES_DESCRIPCION = DESTINO_GENERALES
MR_DES_PONDERACION = 10

MR_LOC_CLAVE = 0000
MR_LOC_DESCRIPCION = LOCALIDAD_GENERALES
MR_LOC_PONDERACION = 10

MR_OCU_CLAVE = 0000
MR_OCU_DESCRIPCION = OCUPACION_GENERALES
MR_OCU_PONDERACION = 10

#DIAS PARA CONSIDERAR EN LAS TRANSACCIONES VS FECHA DE OPERACION
DIAS_OPERACION = 3

#OPERACIONES CON IZEL STI
ESTATUS_ALTA_IZEL_ID = 100000000004
ESTATUS_BAJA_IZEL_ID = 100000000003
APLICACION_IZEL_ID = AHT


#TIPO CUENTAS
TIPO_CUENTA_BLU = CUENTA_BLU
TIPO_CUENTA_AHORRO = AHORRO
TIPO_CUENTA_REFERENCIADA = REFERENCIADA
TIPO_CUENTA_ENTRADA = ENTRADA
TIPO_CUENTA_SALIDA = SALIDA
TIPO_CUENTA_TRASPASO = TRASPASO

#PLAZAS
PLAZA_DISPONIBLE = 1
PLAZA_NO_DISPONIBLE = 0

#TIPO CUENTAS AHORRO
TIPO_CUENTA_AHO_N1 = CTA_N1
TIPO_CUENTA_AHO_N2 = CTA_N2
TIPO_CUENTA_AHO_N3 = CTA_N3
TIPO_CUENTA_AHO_N4 = CTA_N4

MEDIO_PAGO_VENTANILLA_FACIL=10
MEDIO_PAGO_CAJA_ASP=11
MEDIO_PAGO_SPEI=12
WS_ADMIN_PLA = http://sr-admin-plasticos-ws.integraopciones.mx:8081/admin-plasticos-services
CVE_MOV_DEP_SPEI=ASPDS

BANDERA_DEPOSITOS_NUEVOS = TRUE
BANDERA_DEPOSITOS_TRASPASOS_NUEVOS = TRUE
BANDERA_RETIROS_NUEVOS = TRUE
BANDERA_RETIROS_TRASPASOS_NUEVOS = TRUE

#clave transaccion
CVE_MOV_DEV_SPEI=ASPSD
#Clave tipo transaccion
CVE_TIPO_TRANS_SPEI=DEVOLUCION_SPEI
#id tipo transaccion
ID_TIPO_TRANSACCIONES=0,16,17,18,23,24
UPDATE_TIPO_ACTUALIZACION=34

TIMEOUT_TRANSACCION_PLASTICOS_SEGUNDOS=300

