base.inversiones=360
version.app=2
obs.operacion.pendiente.inversiones=ALTA CUENTA INVERSION
id.cat.operacion.pendiente.inversiones=4
cve.sucursal.virtual=SUCVIRTUAL
id.tipo.ahorro.inversion=1
clave.nombre.inversion=NOM_INVERSION
clave.tipo.cta.padre.inversion=TIPO_CTA_PADRE_INV
clave.concepto.colonia=SOLIC_COLONIA

#claves bitacora inversiones
cve.alta.nombre.inversion=ALTA_NOM_INV
cve.update.nombre.inversion=UPDATE_NOM_INV
cve.traspaso.rendimientos=TRASP_REND_INV
cve.traspaso.capital.reinversion=TRASP_CAPITAL_REINV
cve.alta.no.reinv=ALTA_NO_REINV

cve.ini.proc.trasp.rend=INI_PROC_TRASP_REND
cve.fin.proc.trasp.rend=FIN_PROC_TRASP_REND
cve.ini.proc.reinv=INI_PROC_REINV
cve.fin.proc.reinv=FIN_PROC_REINV

#observaciones en bitacora inversiones
obs.bitacora.inversiones.def=OK|CTA. PADRE: %s
obs.bitacora.inversiones.nombre=OK|CTA. PADRE: %s|NOMBRE: %s|OBS: %s
obs.bitacora.inversiones.alta.no.reinv=OK|CTA. PADRE: %s|OBS: %s
obs.bitacora.inversiones.monto=OK|CTA. PADRE: %s|MONTO: %s

obs.ini.proceso.trasp.rend=Inicia Proceso de traspaso de rendimientos|CTA DESTINO: %s|MONTO: %s
obs.fin.proceso.trasp.rend=Finaliza Proceso de traspaso de rendimientos
obs.ini.proceso.reinv=Inicia Proceso de reinversion
obs.fin.proceso.reinv=Finaliza Proceso de reinversion
obs.ini.proceso.canc.inv=Inicia Proceso de cancelacion de inversion
obs.fin.proceso.canc.inv=Finaliza Proceso de cancelacion de inversion

clave.retiro.traspaso.facil=ASPRE
clave.devolucion.retiro.traspaso.facil=ASPDR

id.deposito.traspaso.ahorro=17

id.banco.traspaso.cuentas=0
id.banco.devolucion=0

ret.trans.codi.id=33
ret.trans.codi.cve=RET_TRANS_CODI
dep.trans.codi.id=34
dep.trans.codi.cve=DEP_TRANS_CODI

#tipos referencia bitacora inversiones
cve.tipo.cta.padre=CUENTA_PADRE
cve.tipo.cta.inversion=CUENTA_INVERSION
cve.tipo.id.persona=ID_SOLICITANTE

#Reinversiones - Campos para insertar en tabla ahorro-no-invertir
reinversiones.ahorro-no-invertir.motivo-id=1
reinversiones.ahorro-no-invertir.observaciones=Lo quiere tener disponible

ip.host.transaccion=172.17.7.164
medio.caja.pago.asp=11

id.clave.banco.asp=90659
usuario.dep.trans.ahorro=5835
caja.dep.trans.ahorro=1
forma.pago.dep.trans.ahorro=4
forma.pago.disp.trans.ahorro=4

operacion.notificacion.sms=TRANSFERENCIA A CUENTA DE INVERSION