#**********************************************
# LINKS A LOS SERVICIOS CONSUMIDOS
# FECHA : 25 JUN 2019
#**********************************************
SERVICIOS_SISCOOP=sr-mule-plasticos.integraopciones.mx
#AHORRO_SIMPLIFICADA_WS=http://sr-simplificadaws.integraopciones.mx:8080/AhorroSimplificadaCeroWS/rest
AHORRO_SIMPLIFICADA_WS=http://sr-ahorrows.integraopciones.mx:8080/AhorroSimplificadaCeroWS/rest
AHORRO_WS = http://sr-ahorrows.integraopciones.mx:8080/AhorroCeroWS/rest
NUCLEO_CARTERA_WS=http://sr-adminseg.integraopciones.mx:8080/NucleoCentralCarteraWS/rest
VENTANILLA_WS = http://sr-ventanillaws.integraopciones.mx:8081/VentanillaFacilWS/rest
PALABRAUSU=ASP
PALABRAHID=a5p2017$

#************************************************
# VALORES DEVUELTOS POR INVOCACION DE LA FUNCION
# DE SPEI
#************************************************
NO_PROCESADA=0
CUENTA_INEXISTENTE=1
CUENTA_BLOQUEADA=2
CUENTA_CANCELADA=3
CUENTA_OTRA_DIVISA=5
CUENTA_NO_PERTENECE_BANCO_EMISOR=6
BENEFICIARIO_NO_RECONOCE_PAGO=13
FALTA_INFORMACION=14
TIPO_PAGO_ERRONEO=15
TIPO_OPERACION_ERRONEA=16
TIPO_CUENTA_NO_CORRESPONDE=17
SOLICITUD_EMISOR=18
CARACTER_INVALIDO=19
SALDO_INSUFICIENTE=30
MONTO_MAXIMO=31
GENERICO=999

ESTATUS_ABONADA=1
ESTATUS_DEVUELTA=2
ESTATUS_CARGADA=3

EJECUCION_NORMAL=0
EJECUCION_ERRONEA=1


#************************************************
#PARA ORQUESTADOR
#************************************************
BANCO_PAGO_CREDITO_CF=21
MEDIO_PAGO_CACAO=11
SERVICIO_BASE_ADMIN_PLASTICOS=http://sr-admin-plasticos-ws.integraopciones.mx:8081/admin-plasticos-services
DEBITO_CON_DEP=Deposito a cuenta de mi debito
DEBITO_CON_RET=Retiro de cuenta de mi debito
VALID_TARJETA_DEB=FALSE
INSERT_MOV_CERO=FALSE
WS_VALIDAR_MONTO_TRANSACCIONAL=http://172.17.7.183:8080/AdminSegWS/rest/validarMontoTransaccional
TIEMPO_ESPERA_VALIDAR_OPERACION=150