value = /opt/wildfly-10.1.0.Final/portal/config
#value = /opt/jboss/wildfly/portal/config
#valueWin = I:/JBOSS/wildfly-10.1.0.Final/portal/config
valueWin = D:/Astorga/D/Servers/wildfly-10.1.0.Final/portal/config